CREATE TABLE IF NOT EXISTS ev (id INTEGER PRIMARY KEY AUTOINCREMENT, ts INTEGER NOT NULL, day TEXT NOT NULL, hour INTEGER, slug TEXT, sid TEXT, event TEXT, section TEXT, lang TEXT, host TEXT, bot INTEGER DEFAULT 0);
CREATE INDEX IF NOT EXISTS ev_day ON ev(day);
CREATE INDEX IF NOT EXISTS ev_sid ON ev(sid);
CREATE TABLE IF NOT EXISTS excluded (sid TEXT PRIMARY KEY, note TEXT, ts INTEGER);
