name = "fisco-worker"
main = "fisco_worker.js"
compatibility_date = "2025-01-01"

# ogni mattina alle 10:00 italiane (8:00 UTC in ora legale)
[triggers]
crons = ["0 8 * * *"]

[[services]]
binding = "LS"
service = "little-shadow-145e"

[[services]]
binding = "TG"
service = "tg-worker"

[[kv_namespaces]]
binding = "FISCO_KV"
id = "1d8d7db930004f9eaa73e17af65b0957"
