import json
# campi: id, nome, cat, zona, lat, lon, prezzo (intero adulto, None=gratis? no: 0=gratis, None=da verificare),
# imp 1-5, fatica 1-3, durata (min), desc, verifica (True se prezzo da confermare), temp (data fine o None)
A=[]
def add(id,nome,cat,zona,lat,lon,prezzo,imp,fat,dur,desc,verifica=False,temp=None):
    A.append(dict(id=id,nome=nome,cat=cat,zona=zona,lat=lat,lon=lon,prezzo=prezzo,imp=imp,fatica=fat,durata=dur,desc=desc,verifica=verifica,temp=temp))

# ---------- BLOCCO 1: insolite / musei particolari ----------
add('illusioni','Museo delle Illusioni',['insolito','museo'],'Monti',41.8946,12.5025,22,3,1,75,'Oltre 70 illusioni ottiche e stanze interattive: divertente per tutte le età.',True)
add('cappuccini','Cripta dei Cappuccini',['insolito','chiesa'],'Via Veneto',41.9044,12.4886,10,3,1,45,'Cappelle decorate con le ossa di migliaia di frati: macabra e unica al mondo.')
add('montemartini','Centrale Montemartini',['insolito','museo','archeologia'],'Ostiense',41.8665,12.4777,None,3,1,75,'Statue romane esposte tra le turbine di una vecchia centrale elettrica.',True)
add('serra_moresca','Serra Moresca di Villa Torlonia',['insolito','parco'],'Nomentano',41.9155,12.5125,None,2,1,45,'Serra ottocentesca in stile Alhambra, con vetrate colorate.',True)
add('museo_luce','Museo della Luce',['insolito','museo'],'Campidoglio',41.8950,12.4800,None,2,1,60,'Fisica della luce raccontata con installazioni da toccare.',True)
add('welcome_rome','Welcome to Rome',['insolito','museo'],'Centro Storico',41.8990,12.4700,None,3,1,60,'Viaggio multimediale nei 2700 anni della città, ottimo come introduzione.',True)
add('barracco','Museo Barracco',['museo','archeologia'],'Centro Storico',41.8967,12.4727,0,2,1,45,'Piccola collezione di sculture egizie, assire, greche e romane.')
add('museo_mura','Museo delle Mura',['insolito','archeologia'],'Appia Antica',41.8733,12.5014,0,2,2,45,'Si cammina dentro Porta San Sebastiano e lungo le Mura Aureliane.')
add('lab_mente','Museo Laboratorio della Mente',['insolito','museo'],'Monte Mario',41.9536,12.4300,None,2,1,75,'Nell\'ex manicomio di Santa Maria della Pietà: toccante e poco conosciuto.',True)
add('anime_purgatorio','Museo delle Anime del Purgatorio',['insolito','chiesa'],'Prati',41.9036,12.4737,0,2,1,20,'Minuscola raccolta di "impronte dall\'aldilà" dentro una chiesa neogotica.')
add('buco_serratura','Buco della Serratura dell\'Aventino',['insolito','panorama'],'Aventino',41.8834,12.4787,0,4,1,20,'San Pietro incorniciato nella serratura dei Cavalieri di Malta.')
add('coppede','Quartiere Coppedè',['insolito','quartiere'],'Trieste',41.9178,12.5028,0,3,1,40,'Architettura fiabesca tra liberty, gotico e medievale.')
add('palazzo_valentini','Domus Romane di Palazzo Valentini',['insolito','archeologia'],'Piazza Venezia',41.8963,12.4834,None,4,1,75,'Case romane sotto un palazzo, rianimate da proiezioni multimediali.',True)
add('case_celio','Case Romane del Celio',['insolito','archeologia'],'Celio',41.8871,12.4924,None,3,1,60,'Abitazioni romane affrescate sotto una basilica.',True)
add('galleria_spada','Galleria Spada',['museo','insolito'],'Campo de\' Fiori',41.8940,12.4715,None,3,1,45,'Famosa per la finta prospettiva di Borromini: 9 metri che sembrano 35.',True)
add('galleria_sciarra','Galleria Sciarra',['insolito'],'Trevi',41.8998,12.4818,0,2,1,15,'Cortile liberty affrescato, nascosto a due passi da via del Corso.')
add('maxxi','MAXXI',['museo'],'Flaminio',41.9286,12.4666,None,3,1,90,'Arte contemporanea nell\'edificio progettato da Zaha Hadid.',True)
add('dreamers','Museum of Dreamers',['insolito','museo'],'Prati',41.9160,12.4600,None,2,1,60,'Stanze immersive e colorate, pensate per le foto.',True)
add('ikono','Ikono',['insolito','museo'],'Pantheon',41.8991,12.4781,None,2,1,60,'Esperienza sensoriale a stanze tematiche.',True)
add('time_elevator','Time Elevator',['insolito','museo'],'Trevi',41.8981,12.4830,None,2,1,45,'Cinema 5D con sedili mobili sulla storia di Roma, adatto ai bambini.',True)

# ---------- BLOCCO 2: imperdibili centro storico ----------
add('colosseo','Colosseo, Foro Romano e Palatino',['archeologia'],'Colosseo',41.8902,12.4922,18,5,3,180,'Il simbolo di Roma e il cuore della città antica, con un unico biglietto.')
add('pantheon','Pantheon',['archeologia','chiesa'],'Pantheon',41.8986,12.4769,7,5,1,45,'Il tempio romano meglio conservato, con la cupola più grande in calcestruzzo mai costruita.')
add('trevi','Fontana di Trevi',['piazza','fontana'],'Trevi',41.9009,12.4833,0,5,1,20,'La fontana più famosa del mondo. Vista libera dalla piazza, 2€ per scendere vicino all\'acqua.')
add('navona','Piazza Navona',['piazza','fontana'],'Navona',41.8992,12.4731,0,5,1,30,'Piazza barocca con la Fontana dei Quattro Fiumi di Bernini.')
add('spagna','Piazza di Spagna e Trinità dei Monti',['piazza'],'Spagna',41.9058,12.4823,0,5,1,30,'La scalinata più famosa di Roma, con la Barcaccia ai suoi piedi.')
add('capitolini','Musei Capitolini e Piazza del Campidoglio',['museo','archeologia'],'Campidoglio',41.8933,12.4828,17,4,2,120,'Il museo pubblico più antico del mondo, nella piazza disegnata da Michelangelo.')
add('castel_santangelo','Castel Sant\'Angelo',['museo','panorama'],'Borgo',41.9031,12.4663,18,4,2,90,'Da mausoleo di Adriano a fortezza dei papi, con terrazza panoramica.')
add('vittoriano','Vittoriano',['panorama','museo'],'Piazza Venezia',41.8946,12.4831,0,4,1,60,'Monumento imponente a ingresso libero; la terrazza panoramica costa 18€.')
add('fori_imperiali','Via dei Fori Imperiali',['archeologia','passeggiata'],'Colosseo',41.8925,12.4876,0,4,1,30,'Passeggiata tra i fori di Cesare, Augusto e Traiano, visibili dalla strada.')
add('ghetto','Ghetto ebraico e Portico d\'Ottavia',['quartiere'],'Ghetto',41.8925,12.4775,0,4,1,45,'Il quartiere ebraico più antico d\'Europa, tra rovine romane e carciofi alla giudia.')
add('popolo','Piazza del Popolo',['piazza'],'Flaminio',41.9107,12.4763,0,4,1,20,'Grande piazza neoclassica con l\'obelisco e le chiese gemelle.')
add('campo_fiori','Campo de\' Fiori',['piazza','mercato'],'Campo de\' Fiori',41.8956,12.4722,0,3,1,20,'Mercato la mattina, vita notturna la sera, con la statua di Giordano Bruno.')
add('bocca_verita','Bocca della Verità',['insolito'],'Foro Boario',41.8881,12.4814,None,3,1,20,'La leggendaria maschera che morde la mano dei bugiardi.',True)
add('torre_argentina','Largo di Torre Argentina',['archeologia'],'Centro Storico',41.8955,12.4768,0,3,1,15,'Area sacra dove fu ucciso Cesare, oggi anche colonia felina.')
add('teatro_marcello','Teatro di Marcello',['archeologia'],'Ghetto',41.8918,12.4798,0,3,1,15,'Teatro romano su cui è stato costruito un palazzo abitato.')
add('isola_tiberina','Isola Tiberina',['passeggiata'],'Trastevere',41.8906,12.4775,0,3,1,20,'L\'unica isola del Tevere, collegata dal ponte romano più antico ancora in uso.')
add('circo_massimo','Circo Massimo',['archeologia','parco'],'Aventino',41.8861,12.4851,0,3,1,20,'Il più grande stadio dell\'antichità, oggi un grande prato.')
add('ara_pacis','Ara Pacis',['museo','archeologia'],'Flaminio',41.9063,12.4755,None,3,1,45,'Altare di Augusto nella teca di Richard Meier.',True)

# ---------- BLOCCO 3: Vaticano e dintorni ----------
add('musei_vaticani','Musei Vaticani e Cappella Sistina',['museo'],'Vaticano',41.9065,12.4536,20,5,3,210,'Una delle collezioni più grandi al mondo, fino al Giudizio di Michelangelo. Online con salta fila 25€.')
add('san_pietro','Basilica di San Pietro',['chiesa'],'Vaticano',41.9022,12.4539,0,5,2,60,'La chiesa più grande della cristianità, con la Pietà di Michelangelo.')
add('piazza_san_pietro','Piazza San Pietro',['piazza'],'Vaticano',41.9022,12.4568,0,5,1,20,'Il colonnato di Bernini abbraccia i fedeli.')
add('cupola','Cupola di San Pietro',['panorama','chiesa'],'Vaticano',41.9021,12.4533,17,4,3,60,'Oltre 500 gradini fino alla vista più famosa di Roma.',True)
add('grotte_vaticane','Grotte Vaticane',['chiesa'],'Vaticano',41.9022,12.4539,0,3,1,30,'Le tombe dei papi sotto la basilica.')
add('necropoli','Necropoli Vaticana (Scavi)',['archeologia','insolito'],'Vaticano',41.9020,12.4530,13,3,2,90,'Visita guidata alla tomba di San Pietro: prenotazione con largo anticipo.',True)
add('giardini_vaticani','Giardini Vaticani',['parco'],'Vaticano',41.9040,12.4500,None,3,2,120,'Visita guidata ai giardini dei papi, solo su prenotazione.',True)
add('ponte_santangelo','Ponte Sant\'Angelo',['passeggiata'],'Borgo',41.9014,12.4664,0,3,1,15,'Il ponte degli angeli di Bernini, davanti al castello.')
add('borgo_pio','Borgo Pio e Passetto di Borgo',['quartiere'],'Borgo',41.9040,12.4610,0,2,1,30,'Viuzze sotto il corridoio segreto che portava i papi al castello.')
add('prati','Prati e Via Cola di Rienzo',['quartiere','shopping'],'Prati',41.9080,12.4640,0,2,1,45,'Quartiere elegante umbertino, ottimo per shopping.')
add('palazzaccio','Palazzo di Giustizia',['architettura'],'Prati',41.9030,12.4700,0,2,1,10,'Il "Palazzaccio", monumentale e controverso.')

json.dump(A,open('attrazioni.json','w',encoding='utf-8'),ensure_ascii=False,indent=1)
ver=sum(1 for a in A if a['verifica'])
print(len(A),'attrazioni |',ver,'con prezzo da verificare')
