# Deutsch. A: id -> (Name oder None, Beschreibung, Name_außen oder None, Beschreibung_außen oder None)
A = {
'illusioni': ('Museum der Illusionen', 'Über 70 optische Täuschungen und interaktive Räume: Spaß für jedes Alter.', None, None),
'cappuccini': ('Kapuzinergruft', 'Kapellen, geschmückt mit den Knochen tausender Mönche: makaber und weltweit einzigartig.', None, None),
'montemartini': (None, 'Römische Statuen zwischen den Turbinen eines alten Elektrizitätswerks.', None, None),
'serra_moresca': ('Maurisches Gewächshaus der Villa Torlonia', 'Gewächshaus aus dem 19. Jahrhundert im Alhambra-Stil, mit bunten Glasfenstern. Im Juli und August geschlossen.', None, None),
'museo_luce': ('Museum des Lichts', 'Die Physik des Lichts, erzählt mit Installationen zum Anfassen.', None, None),
'welcome_rome': (None, 'Multimediale Reise durch 2700 Jahre Stadtgeschichte, ideal als Einstieg.', None, None),
'barracco': ('Museum Barracco', 'Kleine Sammlung ägyptischer, assyrischer, griechischer und römischer Skulpturen.', None, None),
'museo_mura': ('Museum der Stadtmauern', 'Man läuft durch die Porta San Sebastiano und entlang der Aurelianischen Mauer.', None, None),
'lab_mente': ('Museum Labor des Geistes', 'In der ehemaligen Nervenheilanstalt Santa Maria della Pietà: bewegend und wenig bekannt.', None, None),
'anime_purgatorio': ('Museum der Seelen im Fegefeuer', 'Winzige Sammlung von „Abdrücken aus dem Jenseits“ in einer neugotischen Kirche.', None, None),
'buco_serratura': ('Schlüsselloch auf dem Aventin', 'Der Petersdom, eingerahmt im Schlüsselloch der Malteserritter.', None, None),
'coppede': ('Coppedè-Viertel', 'Märchenhafte Architektur zwischen Jugendstil, Gotik und Mittelalter.', None, None),
'palazzo_valentini': ('Römische Häuser im Palazzo Valentini', 'Römische Wohnhäuser unter einem Palast, belebt durch multimediale Projektionen.', None, None),
'case_celio': ('Römische Häuser auf dem Celio', 'Freskierte römische Wohnungen unter einer Basilika.', None, None),
'galleria_spada': (None, 'Berühmt für Borrominis falsche Perspektive: 9 Meter, die wie 35 wirken.', None, None),
'galleria_sciarra': (None, 'Freskierter Jugendstil-Innenhof, versteckt nur ein paar Schritte von der Via del Corso.', None, None),
'maxxi': (None, 'Zeitgenössische Kunst im Gebäude von Zaha Hadid.', None, None),
'dreamers': (None, 'Bunte, immersive Räume, gemacht für Fotos.', None, None),
'ikono': (None, 'Sinneserlebnis in Themenräumen.', None, None),
'time_elevator': (None, '5D-Kino mit beweglichen Sitzen über die Geschichte Roms, ideal für Kinder.', None, None),
'colosseo': ('Kolosseum, Forum Romanum und Palatin', 'Das Wahrzeichen Roms und das Herz der antiken Stadt, mit einem einzigen Ticket.', 'Kolosseum (von außen)', 'Das Kolosseum von außen, mit dem Konstantinsbogen und Blick auf das Forum. Eintritt nicht inbegriffen.'),
'pantheon': (None, 'Der am besten erhaltene römische Tempel, mit der größten je gebauten Betonkuppel.', 'Pantheon (von außen)', 'Die Fassade des Pantheons und die Piazza della Rotonda mit ihrem Brunnen. Eintritt nicht inbegriffen.'),
'trevi': ('Trevi-Brunnen', 'Der berühmteste Brunnen der Welt. Freier Blick vom Platz, 2 € um nah ans Wasser zu gehen.', None, None),
'navona': (None, 'Barocker Platz mit Berninis Vierströmebrunnen.', None, None),
'spagna': ('Spanische Treppe und Trinità dei Monti', 'Die berühmteste Treppe Roms, mit der Barcaccia an ihrem Fuß.', None, None),
'capitolini': ('Kapitolinische Museen und Kapitolsplatz', 'Das älteste öffentliche Museum der Welt, auf dem von Michelangelo entworfenen Platz.', 'Kapitolsplatz und Terrasse über dem Forum', 'Michelangelos Kapitolsplatz und die kostenlose Terrasse über dem Forum Romanum.'),
'castel_santangelo': ('Engelsburg', 'Vom Mausoleum Hadrians zur Festung der Päpste, mit Panoramaterrasse.', 'Engelsburg (von außen)', 'Die Burg von der Engelsbrücke und vom Tiberufer aus. Eintritt nicht inbegriffen.'),
'vittoriano': (None, 'Imposantes Monument mit freiem Eintritt; die Panoramaterrasse kostet 18 €.', None, None),
'fori_imperiali': (None, 'Spaziergang an den Foren von Caesar, Augustus und Trajan vorbei, von der Straße aus sichtbar.', None, None),
'ghetto': ('Jüdisches Ghetto und Portikus der Octavia', 'Das älteste jüdische Viertel Europas, zwischen römischen Ruinen und Artischocken nach jüdischer Art.', None, None),
'popolo': (None, 'Großer klassizistischer Platz mit Obelisk und Zwillingskirchen.', None, None),
'campo_fiori': (None, 'Morgens Markt, abends Nachtleben, mit der Statue von Giordano Bruno.', None, None),
'bocca_verita': ('Mund der Wahrheit', 'Die legendäre Maske, die Lügnern in die Hand beißt.', 'Mund der Wahrheit (vom Portikus)', 'Den Mund der Wahrheit sieht man durch das Gitter des Portikus, auch ohne hineinzugehen.'),
'torre_argentina': (None, 'Der heilige Bezirk, in dem Caesar ermordet wurde, heute auch Katzenkolonie.', None, None),
'teatro_marcello': ('Marcellustheater', 'Römisches Theater, auf dem ein bewohnter Palast errichtet wurde.', None, None),
'isola_tiberina': ('Tiberinsel', 'Die einzige Insel im Tiber, verbunden durch die älteste noch genutzte römische Brücke.', None, None),
'circo_massimo': ('Circus Maximus', 'Das größte Stadion der Antike, heute eine große Wiese.', None, None),
'ara_pacis': (None, 'Der Altar des Augustus im Pavillon von Richard Meier.', 'Ara Pacis (von außen)', 'Der Altar des Augustus, gesehen durch Richard Meiers Glaspavillon.'),
'musei_vaticani': ('Vatikanische Museen und Sixtinische Kapelle', 'Eine der größten Sammlungen der Welt, bis zu Michelangelos Jüngstem Gericht. Online ohne Anstehen 25 €.', None, None),
'san_pietro': ('Petersdom', 'Die größte Kirche der Christenheit, mit Michelangelos Pietà.', None, None),
'piazza_san_pietro': ('Petersplatz', 'Berninis Kolonnaden umarmen die Gläubigen.', None, None),
'cupola': ('Kuppel des Petersdoms', 'Aufzug plus 320 Stufen (10 €) oder 551 Stufen zu Fuß (8 €) zum berühmtesten Ausblick Roms.', None, None),
'grotte_vaticane': ('Vatikanische Grotten', 'Die Gräber der Päpste unter der Basilika.', None, None),
'necropoli': ('Vatikanische Nekropole (Scavi)', 'Führung zum Grab des heiligen Petrus: lange im Voraus buchen.', None, None),
'giardini_vaticani': ('Vatikanische Gärten', 'Führung durch die Gärten der Päpste, nur mit Buchung. Ab 20 €, 40 € mit dem Panoramabus.', None, None),
'ponte_santangelo': ('Engelsbrücke', 'Berninis Engelsbrücke vor der Burg.', None, None),
'borgo_pio': ('Borgo Pio und Passetto di Borgo', 'Gassen unter dem geheimen Gang, der die Päpste zur Burg führte.', None, None),
'prati': ('Prati und Via Cola di Rienzo', 'Elegantes Viertel aus dem späten 19. Jahrhundert, ideal zum Shoppen.', None, None),
'palazzaccio': ('Justizpalast', 'Der „Palazzaccio“, monumental und umstritten.', None, None),
'laterano': ('Lateranbasilika', 'Die Kathedrale Roms, Mutter aller Kirchen der Welt.', None, None),
'santa_maria_maggiore': (None, 'Mosaiken aus dem 5. Jahrhundert und eine vergoldete Decke mit dem ersten Gold aus Amerika.', None, None),
'san_paolo': ('Sankt Paul vor den Mauern', 'Riesige Basilika mit den Porträts aller Päpste und einem prächtigen Kreuzgang.', None, None),
'vincoli': ('San Pietro in Vincoli', 'Michelangelos Moses und die Ketten des heiligen Petrus.', None, None),
'san_clemente': ('San Clemente und seine Unterwelt', 'Drei Ebenen übereinander: mittelalterliche Kirche, Basilika aus dem 4. Jahrhundert und Mithrastempel. Ausgrabungen mit Buchung.', None, None),
'santa_maria_trastevere': (None, 'Eine der ältesten Kirchen Roms, mit goldenen Mosaiken an Fassade und Apsis.', None, None),
'san_luigi': (None, 'Drei Meisterwerke Caravaggios über das Leben des heiligen Matthäus, kostenlos.', None, None),
'sant_ignazio': ("Sant'Ignazio", 'Andrea Pozzos gemalte Scheinkuppel: ein Spiegel in der Mitte enthüllt die Täuschung.', None, None),
'santa_maria_popolo': (None, 'Zwei Caravaggios und die Chigi-Kapelle von Raffael und Bernini.', None, None),
'gesu': ('Il Gesù', 'Barockes Meisterwerk der Jesuiten; täglich um 17:30 Uhr die „Maschine“ des Ignatius-Altars.', None, None),
'minerva': (None, 'Die einzige gotische Kirche Roms, mit Berninis Elefanten davor.', None, None),
'scala_santa': ('Heilige Treppe', 'Die Treppe, die Jesus zu Pilatus hinaufgestiegen sein soll: Gläubige steigen sie auf Knien hinauf.', None, None),
'vittoria': (None, 'Die Verzückung der heiligen Theresa, Berninis Meisterwerk.', None, None),
'sant_agostino': ("Sant'Agostino", 'Caravaggios Madonna der Pilger.', None, None),
'aracoeli': (None, 'Man erreicht sie über 124 Stufen; innen Fresken von Pinturicchio.', None, None),
'santa_cecilia': (None, 'Die Statue der Heiligen, so gemeißelt, wie sie gefunden wurde, und ein seltenes Fresko von Cavallini.', None, None),
'santa_prassede': (None, 'Die Zenokapelle, ganz mit goldenen Mosaiken bedeckt.', None, None),
'quattro_fontane': (None, 'Borrominis Meisterwerk: eine ovale Kuppel, so groß wie ein Pfeiler des Petersdoms.', None, None),
'sant_andrea_quirinale': ("Sant'Andrea al Quirinale", 'Berninis „Perle“, hundert Meter von der Kirche seines Rivalen Borromini entfernt.', None, None),
'santo_stefano_rotondo': (None, 'Runde Kirche aus dem 5. Jahrhundert mit drastischen Märtyrerfresken.', None, None),
'quattro_coronati': (None, 'Befestigtes Kloster mit der Silvesterkapelle und einem versteckten Kreuzgang.', None, None),
'santa_sabina': (None, 'Basilika aus dem 5. Jahrhundert mit originaler Holztür und dem Orangengarten nebenan.', None, None),
'tempietto_bramante': ('Tempietto des Bramante', 'Das Juwel der Renaissance, wo der Überlieferung nach Petrus gekreuzigt wurde.', None, None),
'santa_maria_angeli': (None, 'Michelangelo verwandelte die Diokletiansthermen in eine Kirche; im Boden ein Meridian.', None, None),
'sant_ivo': ("Sant'Ivo alla Sapienza", 'Borrominis Spiralkuppel; meist nur sonntagvormittags geöffnet.', None, None),
'san_lorenzo': ('San Lorenzo vor den Mauern', 'Mittelalterliche Basilika mit Kreuzgang, neben dem Friedhof Verano.', None, None),
'santa_costanza': ('Mausoleum der Santa Costanza', 'Mausoleum aus dem 4. Jahrhundert mit noch heidnischen Weinlese-Mosaiken.', None, None),
'chiostro_bramante': ('Kreuzgang des Bramante', 'Renaissance-Kreuzgang mit Wechselausstellungen und einem Café mit Blick auf Santa Maria della Pace.', None, None),
'cosma_damiano': ('Santi Cosma e Damiano', 'Apsismosaik aus dem 6. Jahrhundert und eine große neapolitanische Krippe aus dem 18. Jahrhundert.', None, None),
'galleria_borghese': (None, 'Bernini und Caravaggio in einer barocken Villa. Buchung Pflicht, 2-Stunden-Zeitfenster.', None, None),
'villa_borghese': (None, 'Roms berühmtester Park: Alleen, See mit Ruderbooten, Fahrrad- und Rikschaverleih.', None, None),
'pincio': ('Pincio-Terrasse', 'Blick auf die Piazza del Popolo und die Kuppeln, herrlich bei Sonnenuntergang.', None, None),
'giardino_aranci': ('Orangengarten', 'Der romantischste Sonnenuntergang Roms, zwischen Orangenbäumen über dem Tiber.', None, None),
'gianicolo': ('Aussichtspunkt Gianicolo', 'Die weiteste Terrasse über der Stadt; mittags wird ein Kanonenschuss abgefeuert.', None, None),
'fontanone': ('Fontanone auf dem Gianicolo', 'Der Prunkbrunnen der Acqua Paola, mit Blick auf Trastevere.', None, None),
'terrazza_caffarelli': ('Caffarelli-Terrasse', 'Terrasse auf dem Kapitol mit Blick über die Dächer und auf den Vittoriano.', None, None),
'parco_acquedotti': ('Park der Aquädukte', 'Bögen römischer Aquädukte mitten in Wiesen: das Rom aus „La Grande Bellezza“.', None, None),
'appia_antica': ('Via Appia Antica', 'Die „Königin der Straßen“: römisches Pflaster, Gräber und Landschaft, zu Fuß oder mit dem Rad.', None, None),
'villa_doria_pamphilj': (None, 'Roms größter Park, bei Römern beliebt zum Joggen und Picknicken.', None, None),
'villa_torlonia': (None, 'Mussolinis Villa: kostenloser Park, Jugendstil-Eulenhäuschen für 10,50 €.', None, None),
'roseto': ('Städtischer Rosengarten', 'Über tausend Rosensorten, nur im Frühling geöffnet.', None, None),
'villa_celimontana': (None, 'Ruhiger Park nur ein paar Schritte vom Kolosseum, mit einem ägyptischen Obelisken.', None, None),
'villa_sciarra': (None, 'Kleiner romantischer Garten mit Brunnen und Statuen, bei Touristen fast unbekannt.', None, None),
'villa_ada': (None, 'Großer Naturpark mit See, ehemalige königliche Residenz.', None, None),
'caffarella': ('Caffarella-Park', 'Römische Campagna in der Stadt: Bauernhöfe, Nymphäen und Ruinen.', None, None),
'orto_botanico': ('Botanischer Garten', 'Botanischer Garten am Fuß des Gianicolo, mit Gewächshäusern und Bambus.', None, None),
'bioparco': (None, 'Roms Zoo, ideal für Reisende mit Kindern.', None, None),
'villa_medici': (None, 'Sitz der Französischen Akademie: Renaissancegärten mit Führung.', None, None),
'zodiaco': ('Aussichtspunkt Zodiaco', 'Der höchste Punkt Roms, weit vom Zentrum: mit Bus oder Taxi erreichbar.', None, None),
'domus_aurea': (None, 'Neros verschütteter Palast, mit VR-Brille, die die Säle zeigt, wie sie waren. Kleine Gruppen, früh buchen.', None, None),
'colosseo_sotterranei': ('Kolosseum: Arena und Untergeschosse', 'Sonderführung dort, wo Gladiatoren und Raubtiere durchkamen, mit Zugang zur Arena.', None, None),
'caracalla': ('Caracalla-Thermen', 'Die gewaltigsten Thermen der Antike, weniger überlaufen als das Forum. Im Sommer Oper.', 'Caracalla-Thermen (von außen)', 'Die imposanten Ruinen der Thermen von der Allee aus. Eintritt nicht inbegriffen.'),
'ostia_antica': (None, 'Ein Pompeji 30 Zugminuten entfernt: Straßen, Tavernen, Theater und intakte Häuser.', None, None),
'palazzo_massimo': ('Römisches Nationalmuseum – Palazzo Massimo', 'Fresken aus der Villa der Livia, der Faustkämpfer vom Quirinal und außergewöhnliche Mosaiken.', None, None),
'terme_diocleziano': ('Diokletiansthermen', 'Riesige römische Thermen mit einem Kreuzgang von Michelangelo.', None, None),
'palazzo_altemps': (None, 'Antike Skulpturen in einem Renaissancepalast, darunter der Ludovisische Thron.', None, None),
'crypta_balbi': (None, 'Wie sich Rom von der Antike zum Mittelalter verwandelte, Schicht für Schicht.', None, None),
'mercati_traiano': ('Trajansmärkte', 'Das „Einkaufszentrum“ des antiken Rom, mit Blick von oben auf die Foren.', None, None),
'carcere_mamertino': ('Mamertinischer Kerker', 'Das Gefängnis, in dem der Überlieferung nach der heilige Petrus saß.', None, None),
'stadio_domiziano': ('Domitiansstadion', 'Das römische Stadion unter der Piazza Navona, das ihre Form erklärt.', None, None),
'vicus_caprarius': ('Vicus Caprarius – Stadt des Wassers', 'Unter dem Trevi-Brunnen ein antikes römisches Haus, durchflossen vom Wasser, das den Brunnen speist.', None, None),
'mausoleo_augusto': ('Augustusmausoleum', 'Das runde Grab des ersten Kaisers, nach Jahrzehnten der Restaurierung wieder geöffnet.', 'Augustusmausoleum (von außen)', 'Das runde Grab des Augustus vom Platz aus.'),
'san_callisto': ('Calixtus-Katakomben', 'Die größten und berühmtesten Katakomben, mit der Papstgruft. Führung inbegriffen.', None, None),
'domitilla': ('Domitilla-Katakomben', 'Katakomben mit einer unterirdischen Basilika und frühchristlichen Fresken. Führung inbegriffen.', None, None),
'san_sebastiano': ('Sebastian-Katakomben', 'Katakomben mit perfekt erhaltenen römischen Mausoleen.', None, None),
'priscilla': ('Priscilla-Katakomben', 'Die älteste bekannte Darstellung der Madonna. Nahe unseren Unterkünften.', None, None),
'cecilia_metella': ('Grabmal der Caecilia Metella', 'Das Festungs-Mausoleum, Symbol der Via Appia.', None, None),
'villa_quintili': ('Villa der Quintilier', 'Riesige, fast menschenleere Kaiservilla abseits der Touristenpfade.', None, None),
'cimitero_acattolico': ('Protestantischer Friedhof und Cestius-Pyramide', 'Der romantische Friedhof von Keats und Shelley, im Schatten einer römischen Pyramide.', None, None),
'monte_testaccio': ('Monte Testaccio (Scherbenberg)', 'Ein Hügel ganz aus zerbrochenen Amphoren: die Müllhalde des antiken Rom. Nur bei gelegentlichen Führungen.', None, None),
'trastevere': (None, 'Kopfsteingassen, Efeu und Trattorien: das römischste Viertel Roms, am schönsten am Abend.', None, None),
'monti': ('Monti-Viertel', 'Das älteste Viertel, heute voller Vintage-Läden, Handwerker und kleiner Plätze.', None, None),
'testaccio': ('Testaccio und sein Markt', 'Das Viertel der echten römischen Küche, mit Markthalle und Streetfood.', None, None),
'via_margutta': (None, 'Die Straße der Künstler und von „Ein Herz und eine Krone“, mit Werkstätten und Galerien.', None, None),
'piazza_mattei': ('Schildkrötenbrunnen', 'Kleiner Renaissancebrunnen auf einem versteckten Plätzchen im Ghetto.', None, None),
'garbatella': (None, 'Gartenstadt der 1920er-Jahre: Häuschen, Innenhöfe und Sozialwohnungen wie auf einer Postkarte.', None, None),
'pigneto': (None, 'Pasolinis Viertel, heute Wandbilder, Bars und alternatives Nachtleben.', None, None),
'via_giulia': (None, 'Kerzengerade Renaissancestraße mit Adelspalästen und dem Farnese-Bogen.', None, None),
'piazza_farnese': (None, 'Eleganter Platz mit Michelangelos Palast, heute Französische Botschaft.', None, None),
'via_coronari': (None, 'Die Straße der Antiquitätenhändler, ein paar Schritte von der Piazza Navona.', None, None),
'san_lorenzo_quartiere': ('Viertel San Lorenzo', 'Das Universitätsviertel, Wandbilder und Bars. Wenige Schritte von unseren Unterkünften.', None, None),
'eur': (None, 'Die rationalistische Stadt für die Weltausstellung 1942, mit dem „quadratischen Kolosseum“.', None, None),
'ostiense_street_art': ('Ostiense und der Gasometer', 'Industriearchäologie und riesige Wandbilder, vom Gasometer bis zu den ehemaligen Großmärkten.', None, None),
'tor_marancia': (None, 'Zweiundzwanzig Sozialwohnblocks, bemalt von internationalen Street-Artists.', None, None),
'governo_vecchio': (None, 'Vintage-Läden und Werkstätten zwischen Navona und Chiesa Nuova.', None, None),
'quadraro': ('Quadraro und das MURo', 'Freiluftmuseum für Urban Art in einem Arbeiterviertel der Resistenza.', None, None),
'porta_portese': ('Markt von Porta Portese', 'Roms berühmtester Flohmarkt: nur sonntagvormittags.', None, None),
'mercato_centrale': ('Mercato Centrale Termini', 'Food Hall mit den besten Genusshandwerkern unter einem Dach.', None, None),
'mercato_trionfale': ('Markt Trionfale', 'Die Markthalle der Römer, ein paar Schritte von den Vatikanischen Museen.', None, None),
'campagna_amica': ('Bauernmarkt Campagna Amica am Circus Maximus', 'Produkte der Bauern aus Latium, samstags und sonntags.', None, None),
'cooking_class': ('Römischer Kochkurs', 'Du lernst frische Pasta, Tiramisù oder Pizza zu machen und isst dann, was du gekocht hast. Meist 60-90 €.', None, None),
'food_tour': ('Food-Tour in Trastevere oder Testaccio', 'Geführte Verkostungen von Supplì, Pizza al taglio, Käse und Gelato. Meist 60-90 €.', None, None),
'vespa_tour': ('Tour mit Vespa oder Oldtimer-Fiat 500', 'Rom wie in „Ein Herz und eine Krone“, mit Fahrer oder selbst am Steuer. Meist 80-150 €.', None, None),
'golf_cart': ('Golfcart-Tour', 'Die Altstadt ohne Anstrengung: ideal für alle, die wenig laufen.', None, None),
'bici_appia': ('Via Appia mit dem Rad', 'Fahrradverleih am Appia Info Point und los zwischen Gräbern und römischem Pflaster.', None, None),
'crociera_tevere': ('Bootsfahrt auf dem Tiber', 'Rom vom Fluss aus, auch mit Abendessen an Bord.', None, None),
'cinecitta': (None, 'Besuch der Studios von Fellini und der Filmkulissen des antiken Rom.', None, None),
'explora': ('Explora – Kindermuseum', 'Interaktives Museum, in dem Kinder alles selbst machen.', None, None),
'opera_caracalla': ('Oper in den Caracalla-Thermen', 'Oper und Ballett unter freiem Himmel zwischen den Ruinen der Thermen. Nur im Sommer.', None, None),
}
G = {
'tivoli': ("Tivoli: Villa d'Este und Hadriansvilla", 'Zwei UNESCO-Stätten an einem Tag: die Villa Kaiser Hadrians und der Garten der hundert Brunnen.', ['Hadriansvilla', "Villa d'Este", 'Altstadt von Tivoli'], 'Montagvormittag geschlossen'),
'pompei': ('Pompeji', 'Die vom Vesuv verschüttete Stadt. Frecciarossa bis Neapel, dann Circumvesuviana: ein langer, aber unvergesslicher Tag.', ['Ausgrabungen von Pompeji'], None),
'firenze': ('Florenz an einem Tag', 'Mit dem Frecciarossa in anderthalb Stunden: das Beste der Renaissance an einem Tag.', ['Dom', 'Ponte Vecchio', 'Piazza della Signoria', 'Uffizien (optional)'], None),
'orvieto': (None, 'Etruskerstadt auf einem Tuffsteinfelsen, mit einem der schönsten gotischen Dome Italiens und einem Höhlenlabyrinth.', ['Dom', 'Brunnen des heiligen Patrick', 'Unterirdisches Orvieto'], None),
'napoli': ('Neapel an einem Tag', 'Eine Stunde und zehn Minuten Frecciarossa in die lebendigste Stadt Italiens, und zu ihrer Pizza.', ['Altstadt', 'Verhüllter Christus', 'Uferpromenade', 'Pizza'], None),
'castelli': ('Castelli Romani', 'Orte auf vulkanischen Hügeln: Wein aus Frascati, Porchetta aus Ariccia, Walderdbeeren aus Nemi und der Papstpalast.', ['Frascati', 'Castel Gandolfo', 'Ariccia', 'Nemi'], 'Der Papstpalast in Castel Gandolfo kostet Eintritt'),
'tuscia': ('Civita di Bagnoregio und Park der Ungeheuer', 'Die „sterbende Stadt“ auf ihrem Tuffsporn und der Garten der monströsen Skulpturen, der Dalí begeisterte. Auto nötig.', ['Civita di Bagnoregio', 'Heiliger Wald von Bomarzo'], None),
'assisi': (None, 'Die Stadt des heiligen Franziskus, mit der von Giotto ausgemalten Basilika.', ['Basilika San Francesco', 'Altstadt'], None),
'cerveteri': ('Cerveteri: etruskische Nekropole', 'Eine etruskische Totenstadt, UNESCO-Welterbe, mit Gräbern in Hausform. Das Meer von Ladispoli ist nah.', ['Banditaccia-Nekropole', 'Museo Cerite'], None),
'tarquinia': ('Tarquinia: bemalte Gräber', 'Die schönsten freskierten Etruskergräber der Welt, mit Farben, die nach 2500 Jahren noch leuchten.', ['Monterozzi-Nekropole', 'Nationalmuseum Tarquinia'], None),
'ninfa': ('Garten von Ninfa und Sermoneta', 'Der „romantischste Garten der Welt“ zwischen den Ruinen einer mittelalterlichen Stadt. Nur an einigen Tagen, mit Buchung.', ['Garten von Ninfa', 'Dorf Sermoneta'], 'Saisonal geöffnet, April bis November'),
'sperlonga': (None, 'Weißes Dorf hoch über dem Meer und einige der schönsten Strände Latiums. Ideal im Sommer.', ['weißes Dorf', 'Strand', 'Tiberius-Grotte'], 'Empfohlen von Juni bis September'),
'viterbo': (None, 'Die mittelalterliche Papststadt, mit intakten Vierteln und freien Thermalquellen zum Baden.', ['Papstpalast', 'Viertel San Pellegrino', 'Unterirdisches Viterbo', 'Thermen'], None),
'bracciano': ('See und Burg von Bracciano', 'Mittelalterliche Burg an einem Vulkansee, mit Uferspaziergang und Mittagessen mit Seefisch.', ['Burg Orsini-Odescalchi', 'Seepromenade'], None),
'subiaco': ('Subiaco: Klöster des heiligen Benedikt', 'Klöster, die am Felsen kleben, wo Benedikt seinen Orden gründete.', ['Sacro Speco', 'Kloster Santa Scolastica'], None),
'montecassino': ('Abtei Montecassino', 'Die Abtei des heiligen Benedikt, zerstört und nach der Schlacht von 1944 wiederaufgebaut.', ['Abtei', 'polnischer Soldatenfriedhof'], None),
'mare_ostia': ('Meer in Ostia', 'Der Strand der Römer, mit dem Stadtticket erreichbar. Nur im Sommer.', ['Strand'], None),
}
S = {
'trastevere': (None, 'Das Herz des römischen Abends: Aperitivo auf der Piazza San Calisto, Abendessen in der Trattoria, dann die Stufen der Piazza Trilussa.'),
'monti': ('Monti-Viertel', 'Aperitivo auf der Piazza Madonna dei Monti zwischen Römern und Touristen, dann Abendessen rund um die Via Panisperna.'),
'campo_navona': ("Campo de' Fiori und Navona", "Weinbars in der Via del Governo Vecchio und auf der Piazza del Fico, Abendessen nahe Navona, Nachtleben am Campo de' Fiori."),
'ghetto': ('Jüdisches Ghetto', 'Römisch-jüdisches Abendessen: Artischocken nach jüdischer Art und frittierter Kabeljau zwischen Portikus der Octavia und Via del Portico.'),
'testaccio': (None, 'Die echteste römische Küche, vom Ochsenschwanz bis Cacio e Pepe; danach Bars bis spät.'),
'pigneto': (None, 'Alternative Fußgängerzone, Naturweine und Craft-Bier. Nahe unseren Unterkünften.'),
'tridente': ('Spanische Treppe und Piazza del Popolo', 'Eleganter Aperitivo und Terrassen mit Aussicht zwischen Via Margutta und Piazza del Popolo.'),
'prati': (None, 'Feine Aperitivo-Bars und ruhige Restaurants, perfekt nach einem Tag im Vatikan.'),
'san_lorenzo': (None, 'Das Universitätsviertel: günstig, lebendig, voller Trattorien und Pubs. Nur ein paar Schritte von zu Hause.'),
'ostiense': (None, 'Ehemaliges Industriegebiet mit Bars, Restaurants und Clubs; Eataly für alles an einem Ort.'),
'ponte_milvio': (None, 'Der Aperitivo der jungen Römer, mit der Brücke der Liebesschlösser.'),
'piazza_bologna': ('Gegend Piazza Bologna (nahe Unterkunft)', 'Für einen ruhigen Abend nahe unseren Unterkünften: unsere Tipps findest du im Bereich Essen.'),
}
