# English. A: id -> (name or None, desc, outside_name or None, outside_desc or None)
A = {
'illusioni': ('Museum of Illusions', 'Over 70 optical illusions and interactive rooms: fun for all ages.', None, None),
'cappuccini': ('Capuchin Crypt', 'Chapels decorated with the bones of thousands of friars: macabre and unique in the world.', None, None),
'montemartini': (None, 'Roman statues displayed among the turbines of an old power station.', None, None),
'serra_moresca': ('Moorish Greenhouse at Villa Torlonia', '19th-century greenhouse in Alhambra style, with coloured glass. Closed in July and August.', None, None),
'museo_luce': ('Museum of Light', 'The physics of light told through hands-on installations.', None, None),
'welcome_rome': (None, "A multimedia journey through the city's 2,700 years: a great introduction.", None, None),
'barracco': ('Barracco Museum', 'Small collection of Egyptian, Assyrian, Greek and Roman sculpture.', None, None),
'museo_mura': ('Museum of the Walls', 'Walk inside Porta San Sebastiano and along the Aurelian Walls.', None, None),
'lab_mente': ('Museum Laboratory of the Mind', 'In the former Santa Maria della Pietà asylum: moving and little known.', None, None),
'anime_purgatorio': ('Museum of the Souls of Purgatory', 'A tiny collection of "imprints from the afterlife" inside a neo-Gothic church.', None, None),
'buco_serratura': ('Aventine Keyhole', "St Peter's dome framed in the keyhole of the Knights of Malta.", None, None),
'coppede': ('Coppedè District', 'Fairy-tale architecture mixing Art Nouveau, Gothic and medieval.', None, None),
'palazzo_valentini': ('Roman Houses of Palazzo Valentini', 'Roman houses beneath a palace, brought back to life by multimedia projections.', None, None),
'case_celio': ('Roman Houses of the Celio', 'Frescoed Roman homes beneath a basilica.', None, None),
'galleria_spada': (None, "Famous for Borromini's false perspective: 9 metres that look like 35.", None, None),
'galleria_sciarra': (None, 'A frescoed Art Nouveau courtyard hidden a few steps from Via del Corso.', None, None),
'maxxi': (None, 'Contemporary art in the building designed by Zaha Hadid.', None, None),
'dreamers': (None, 'Colourful immersive rooms designed for photos.', None, None),
'ikono': (None, 'A sensory experience through themed rooms.', None, None),
'time_elevator': (None, 'A 5D cinema with moving seats about the history of Rome, great for children.', None, None),
'colosseo': ('Colosseum, Roman Forum and Palatine', 'The symbol of Rome and the heart of the ancient city, all with one ticket.', 'Colosseum (from outside)', 'The Colosseum from outside, with the Arch of Constantine and the view over the Forum. Entry not included.'),
'pantheon': (None, 'The best-preserved Roman temple, with the largest concrete dome ever built.', 'Pantheon (from outside)', 'The facade of the Pantheon and Piazza della Rotonda with its fountain. Entry not included.'),
'trevi': ('Trevi Fountain', "The world's most famous fountain. Free view from the square, €2 to go down close to the water.", None, None),
'navona': (None, "Baroque square with Bernini's Fountain of the Four Rivers.", None, None),
'spagna': ('Spanish Steps and Trinità dei Monti', 'The most famous staircase in Rome, with the Barcaccia fountain at its foot.', None, None),
'capitolini': ('Capitoline Museums and Piazza del Campidoglio', 'The oldest public museum in the world, in the square designed by Michelangelo.', 'Piazza del Campidoglio and Forum terrace', "Michelangelo's Piazza del Campidoglio and the free terrace over the Roman Forum."),
'castel_santangelo': (None, "From Hadrian's mausoleum to papal fortress, with a panoramic terrace.", "Castel Sant'Angelo (from outside)", 'The castle seen from the Bridge of Angels and the riverside. Entry not included.'),
'vittoriano': (None, 'An imposing monument with free entry; the panoramic terrace costs €18.', None, None),
'fori_imperiali': (None, 'A walk past the forums of Caesar, Augustus and Trajan, visible from the street.', None, None),
'ghetto': ("Jewish Ghetto and Portico d'Ottavia", "Europe's oldest Jewish quarter, among Roman ruins and Jewish-style artichokes.", None, None),
'popolo': (None, 'A grand neoclassical square with its obelisk and twin churches.', None, None),
'campo_fiori': (None, 'Market in the morning, nightlife in the evening, with the statue of Giordano Bruno.', None, None),
'bocca_verita': ('Mouth of Truth', 'The legendary mask that bites the hands of liars.', 'Mouth of Truth (from the portico)', 'You can see the Mouth of Truth through the portico gate, even without going in.'),
'torre_argentina': (None, 'The sacred area where Caesar was killed, today also a cat sanctuary.', None, None),
'teatro_marcello': ('Theatre of Marcellus', 'A Roman theatre with an inhabited palace built on top of it.', None, None),
'isola_tiberina': ('Tiber Island', "The Tiber's only island, linked by the oldest Roman bridge still in use.", None, None),
'circo_massimo': ('Circus Maximus', "Antiquity's largest stadium, today a huge lawn.", None, None),
'ara_pacis': (None, "Augustus' altar in Richard Meier's glass pavilion.", 'Ara Pacis (from outside)', "Augustus' altar seen through Richard Meier's glass pavilion."),
'musei_vaticani': ('Vatican Museums and Sistine Chapel', "One of the largest collections in the world, up to Michelangelo's Last Judgement. Skip-the-line online €25.", None, None),
'san_pietro': ("St Peter's Basilica", "The largest church in Christendom, with Michelangelo's Pietà.", None, None),
'piazza_san_pietro': ("St Peter's Square", "Bernini's colonnade embraces the faithful.", None, None),
'cupola': ("St Peter's Dome", 'Lift plus 320 steps (€10) or 551 steps on foot (€8) to the most famous view of Rome.', None, None),
'grotte_vaticane': ('Vatican Grottoes', 'The tombs of the popes beneath the basilica.', None, None),
'necropoli': ('Vatican Necropolis (Scavi)', "Guided visit to St Peter's tomb: book well in advance.", None, None),
'giardini_vaticani': ('Vatican Gardens', "Guided visit to the popes' gardens, booking only. From €20, €40 with the open bus.", None, None),
'ponte_santangelo': ("Ponte Sant'Angelo", "Bernini's bridge of angels, in front of the castle.", None, None),
'borgo_pio': ('Borgo Pio and Passetto di Borgo', 'Little streets beneath the secret corridor that led the popes to the castle.', None, None),
'prati': ('Prati and Via Cola di Rienzo', 'An elegant late-19th-century district, great for shopping.', None, None),
'palazzaccio': ('Palace of Justice', 'The "Palazzaccio", monumental and controversial.', None, None),
'laterano': ('St John Lateran', 'The cathedral of Rome, mother of all churches in the world.', None, None),
'santa_maria_maggiore': (None, '5th-century mosaics and a gilded ceiling made with the first gold from the Americas.', None, None),
'san_paolo': ("St Paul Outside the Walls", 'An immense basilica with portraits of every pope and a splendid cloister.', None, None),
'vincoli': ('San Pietro in Vincoli', "Michelangelo's Moses and the chains of St Peter.", None, None),
'san_clemente': ('San Clemente and its underground', 'Three layers: a medieval church, a 4th-century basilica and a temple of Mithras. Excavations by booking.', None, None),
'santa_maria_trastevere': (None, 'One of the oldest churches in Rome, with golden mosaics on the facade and apse.', None, None),
'san_luigi': (None, 'Three Caravaggio masterpieces on the life of St Matthew, for free.', None, None),
'sant_ignazio': ("Sant'Ignazio", "Andrea Pozzo's painted false dome: a mirror in the middle reveals the trick.", None, None),
'santa_maria_popolo': (None, 'Two Caravaggios and the Chigi Chapel by Raphael and Bernini.', None, None),
'gesu': ('Church of the Gesù', 'The Jesuits\' Baroque masterpiece; every day at 5:30 pm the "machine" of St Ignatius\' altar.', None, None),
'minerva': (None, "Rome's only Gothic church, with Bernini's little elephant in front.", None, None),
'scala_santa': ('Holy Stairs', 'The stairs Jesus is said to have climbed to Pilate: pilgrims go up on their knees.', None, None),
'vittoria': (None, "The Ecstasy of St Teresa, Bernini's masterpiece.", None, None),
'sant_agostino': ("Sant'Agostino", "Caravaggio's Madonna of the Pilgrims.", None, None),
'aracoeli': (None, 'Reached by climbing 124 steps; inside, frescoes by Pinturicchio.', None, None),
'santa_cecilia': (None, 'The statue of the saint carved as she was found, and a rare fresco by Cavallini.', None, None),
'santa_prassede': (None, 'The Chapel of St Zeno, entirely covered in golden mosaics.', None, None),
'quattro_fontane': (None, "Borromini's masterpiece: an oval dome as big as one pillar of St Peter's.", None, None),
'sant_andrea_quirinale': ("Sant'Andrea al Quirinale", 'Bernini\'s "pearl", a hundred metres from his rival Borromini\'s church.', None, None),
'santo_stefano_rotondo': (None, 'A round 5th-century church with graphic frescoes of martyrs.', None, None),
'quattro_coronati': (None, 'A fortified monastery with the Chapel of St Sylvester and a hidden cloister.', None, None),
'santa_sabina': (None, 'A 5th-century basilica with its original wooden door and the Orange Garden next door.', None, None),
'tempietto_bramante': ("Bramante's Tempietto", 'The jewel of the Renaissance, where tradition says Peter was crucified.', None, None),
'santa_maria_angeli': (None, 'Michelangelo turned the Baths of Diocletian into a church; a meridian line on the floor.', None, None),
'sant_ivo': ("Sant'Ivo alla Sapienza", "Borromini's spiral dome; usually open only on Sunday mornings.", None, None),
'san_lorenzo': ('San Lorenzo Outside the Walls', 'A medieval basilica with a cloister, next to the Verano cemetery.', None, None),
'santa_costanza': ('Mausoleum of Santa Costanza', 'A 4th-century mausoleum with still-pagan grape harvest mosaics.', None, None),
'chiostro_bramante': ('Cloister of Bramante', 'A Renaissance cloister hosting exhibitions, with a café overlooking Santa Maria della Pace.', None, None),
'cosma_damiano': ('Santi Cosma e Damiano', 'A 6th-century apse mosaic and a large 18th-century Neapolitan nativity scene.', None, None),
'galleria_borghese': ('Borghese Gallery', 'Bernini and Caravaggio in a Baroque villa. Booking required, 2-hour slots.', None, None),
'villa_borghese': (None, "Rome's most famous park: avenues, a lake with rowing boats, bike and rickshaw hire.", None, None),
'pincio': ('Pincio Terrace', 'Views over Piazza del Popolo and the domes, stunning at sunset.', None, None),
'giardino_aranci': ('Orange Garden', 'The most romantic sunset in Rome, among orange trees above the Tiber.', None, None),
'gianicolo': ('Janiculum Terrace', 'The widest view over the city; a cannon is fired at noon.', None, None),
'fontanone': ('Fontanone on the Janiculum', 'The monumental Acqua Paola fountain, overlooking Trastevere.', None, None),
'terrazza_caffarelli': ('Caffarelli Terrace', 'A terrace on the Capitoline Hill overlooking the rooftops and the Vittoriano.', None, None),
'parco_acquedotti': ('Park of the Aqueducts', 'Arches of Roman aqueducts in open meadows: the Rome of "The Great Beauty".', None, None),
'appia_antica': ('Appian Way', 'The "queen of roads": Roman paving stones, tombs and countryside, on foot or by bike.', None, None),
'villa_doria_pamphilj': (None, "Rome's largest park, loved by locals for running and picnics.", None, None),
'villa_torlonia': (None, "Mussolini's villa: free park, Art Nouveau House of the Owls for €10.50.", None, None),
'roseto': ('Municipal Rose Garden', 'Over a thousand varieties of roses, open only in spring.', None, None),
'villa_celimontana': (None, 'A quiet park a stone\'s throw from the Colosseum, with an Egyptian obelisk.', None, None),
'villa_sciarra': (None, 'A small romantic garden with fountains and statues, almost unknown to tourists.', None, None),
'villa_ada': (None, 'A large natural park with a lake, a former royal residence.', None, None),
'caffarella': ('Caffarella Park', 'Roman countryside in the city: farms, nymphaea and ruins.', None, None),
'orto_botanico': ('Botanical Garden', 'A botanical garden at the foot of the Janiculum, with greenhouses and bamboo.', None, None),
'bioparco': (None, "Rome's zoo, ideal for those travelling with children.", None, None),
'villa_medici': (None, 'Home of the French Academy: Renaissance gardens with guided tours.', None, None),
'zodiaco': ('Zodiaco Viewpoint', 'The highest point in Rome, far from the centre: reached by bus or taxi.', None, None),
'domus_aurea': (None, "Nero's buried palace, with a VR headset showing the rooms as they were. Small groups, book early.", None, None),
'colosseo_sotterranei': ('Colosseum: arena and underground', 'A special tour where gladiators and beasts passed, with access to the arena.', None, None),
'caracalla': ('Baths of Caracalla', 'The most impressive baths of antiquity, less crowded than the Forum. Opera in summer.', 'Baths of Caracalla (from outside)', 'The imposing ruins of the baths seen from the avenue. Entry not included.'),
'ostia_antica': (None, 'A Pompeii 30 minutes away by train: streets, taverns, a theatre and intact houses.', None, None),
'palazzo_massimo': ('National Roman Museum – Palazzo Massimo', "Frescoes from Livia's villa, the Boxer at Rest and extraordinary mosaics.", None, None),
'terme_diocleziano': ('Baths of Diocletian', 'Huge Roman baths with a cloister by Michelangelo.', None, None),
'palazzo_altemps': (None, 'Ancient sculpture in a Renaissance palace, including the Ludovisi Throne.', None, None),
'crypta_balbi': (None, 'How Rome changed from antiquity to the Middle Ages, layer by layer.', None, None),
'mercati_traiano': ("Trajan's Markets", 'The "shopping mall" of ancient Rome, with a view down over the Forums.', None, None),
'carcere_mamertino': ('Mamertine Prison', 'The prison where tradition says St Peter was held.', None, None),
'stadio_domiziano': ('Stadium of Domitian', 'The Roman stadium hidden beneath Piazza Navona, which explains its shape.', None, None),
'vicus_caprarius': ('Vicus Caprarius – City of Water', 'Under Trevi, an ancient Roman house crossed by the water that feeds the fountain.', None, None),
'mausoleo_augusto': ('Mausoleum of Augustus', 'The round tomb of the first emperor, reopened after decades of restoration.', 'Mausoleum of Augustus (from outside)', 'The round tomb of Augustus seen from the square.'),
'san_callisto': ('Catacombs of San Callisto', 'The largest and most famous catacombs, with the crypt of the popes. Guided tour included.', None, None),
'domitilla': ('Catacombs of Domitilla', 'Catacombs with an underground basilica and early Christian frescoes. Guided tour included.', None, None),
'san_sebastiano': ('Catacombs of San Sebastiano', 'Catacombs with perfectly preserved Roman mausoleums.', None, None),
'priscilla': ('Catacombs of Priscilla', 'The oldest known image of the Madonna. Close to our properties.', None, None),
'cecilia_metella': ('Tomb of Cecilia Metella', 'The fortress-mausoleum that symbolises the Appian Way.', None, None),
'villa_quintili': ('Villa of the Quintilii', 'A huge, almost deserted imperial villa, off the tourist trail.', None, None),
'cimitero_acattolico': ('Non-Catholic Cemetery and Pyramid of Cestius', 'The romantic cemetery of Keats and Shelley, in the shadow of a Roman pyramid.', None, None),
'monte_testaccio': ('Monte Testaccio (Hill of Shards)', 'A hill made entirely of broken amphorae: the rubbish dump of ancient Rome. Only on occasional guided tours.', None, None),
'trastevere': (None, 'Cobbled lanes, ivy and trattorias: the most Roman district of Rome, at its best in the evening.', None, None),
'monti': ('Monti district', 'The oldest district, now full of vintage shops, artisans and little squares.', None, None),
'testaccio': ('Testaccio and its market', 'The district of genuine Roman cooking, with its covered market and street food.', None, None),
'via_margutta': (None, 'The street of artists and of "Roman Holiday", with workshops and galleries.', None, None),
'piazza_mattei': ('Turtle Fountain', 'A small Renaissance fountain in a hidden little square of the Ghetto.', None, None),
'garbatella': (None, 'A 1920s garden city: cottages, courtyards and picture-postcard social housing.', None, None),
'pigneto': (None, "Pasolini's district, now murals, bars and alternative nightlife.", None, None),
'via_giulia': (None, 'A dead-straight Renaissance street with noble palaces and the Farnese arch.', None, None),
'piazza_farnese': (None, "An elegant square with Michelangelo's palace, today the French Embassy.", None, None),
'via_coronari': (None, 'The street of antique dealers, steps from Piazza Navona.', None, None),
'san_lorenzo_quartiere': ('San Lorenzo district', 'The university district, murals and bars. A few steps from our properties.', None, None),
'eur': (None, 'The rationalist city built for the 1942 Exposition, with the "Square Colosseum".', None, None),
'ostiense_street_art': ('Ostiense and the Gasometer', 'Industrial archaeology and huge murals, from the Gasometer to the former wholesale markets.', None, None),
'tor_marancia': (None, 'Twenty-two social housing blocks painted by international street artists.', None, None),
'governo_vecchio': (None, 'Vintage shops and workshops between Navona and Chiesa Nuova.', None, None),
'quadraro': ('Quadraro and the MURo', 'An open-air urban art museum in a working-class district of the Resistance.', None, None),
'porta_portese': ('Porta Portese market', "Rome's most famous flea market: Sunday mornings only.", None, None),
'mercato_centrale': ('Mercato Centrale at Termini', 'A food hall with the best artisan producers under one roof.', None, None),
'mercato_trionfale': ('Trionfale Market', "The locals' covered market, steps from the Vatican Museums.", None, None),
'campagna_amica': ('Campagna Amica farmers\' market at Circus Maximus', "Produce from Lazio's farmers, on Saturdays and Sundays.", None, None),
'cooking_class': ('Roman cooking class', 'Learn to make fresh pasta, tiramisù or pizza, then eat what you cooked. Usually €60-90.', None, None),
'food_tour': ('Food tour in Trastevere or Testaccio', 'Guided tastings of supplì, pizza by the slice, cheese and gelato. Usually €60-90.', None, None),
'vespa_tour': ('Vespa or vintage Fiat 500 tour', 'Rome as in "Roman Holiday", with a driver or behind the wheel. Usually €80-150.', None, None),
'golf_cart': ('Golf cart tour', 'The historic centre without effort: ideal for those who walk little.', None, None),
'bici_appia': ('Appian Way by bike', 'Rent a bike at the Appia Info Point and ride among tombs and Roman paving stones.', None, None),
'crociera_tevere': ('Tiber boat trip', 'Rome seen from the river, also with dinner on board.', None, None),
'cinecitta': (None, "Visit Fellini's studios and the ancient Rome film sets.", None, None),
'explora': ("Explora – Children's Museum", 'An interactive museum where children do everything themselves.', None, None),
'opera_caracalla': ('Opera at the Baths of Caracalla', 'Open-air opera and ballet among the ruins of the baths. Summer only.', None, None),
}
G = {
'tivoli': ("Tivoli: Villa d'Este and Hadrian's Villa", "Two UNESCO sites in one day: Emperor Hadrian's villa and the garden of a hundred fountains.", ["Hadrian's Villa", "Villa d'Este", 'Tivoli old town'], 'Closed on Monday mornings'),
'pompei': ('Pompeii', 'The city buried by Vesuvius. Frecciarossa to Naples then the Circumvesuviana: a long but unforgettable day.', ['Pompeii excavations'], None),
'firenze': ('Florence in a day', 'The Frecciarossa gets you there in an hour and a half: the best of the Renaissance in one day.', ['Duomo', 'Ponte Vecchio', 'Piazza della Signoria', 'Uffizi (optional)'], None),
'orvieto': (None, 'An Etruscan town on a tufa cliff, with one of the finest Gothic cathedrals in Italy and a maze of caves.', ['Duomo', "St Patrick's Well", 'Underground Orvieto'], None),
'napoli': ('Naples in a day', "An hour and ten minutes by Frecciarossa to Italy's liveliest city, and its pizza.", ['historic centre', 'Veiled Christ', 'seafront', 'pizza'], None),
'castelli': ('Castelli Romani', 'Towns on volcanic hills: Frascati wine, Ariccia porchetta, Nemi strawberries and the papal palace.', ['Frascati', 'Castel Gandolfo', 'Ariccia', 'Nemi'], 'The Papal Palace at Castel Gandolfo charges admission'),
'tuscia': ('Civita di Bagnoregio and the Park of Monsters', '"The dying town" on its tufa spur and the garden of monstrous sculptures that enchanted Dalí. A car is needed.', ['Civita di Bagnoregio', 'Sacred Grove of Bomarzo'], None),
'assisi': (None, 'The town of St Francis, with the basilica frescoed by Giotto.', ['Basilica of St Francis', 'old town'], None),
'cerveteri': ('Cerveteri: Etruscan necropolis', 'A UNESCO Etruscan city of the dead, with house-shaped tombs. The Ladispoli seaside is nearby.', ['Banditaccia Necropolis', 'Cerite Museum'], None),
'tarquinia': ('Tarquinia: painted tombs', 'The most beautiful frescoed Etruscan tombs in the world, colours still vivid after 2,500 years.', ['Monterozzi Necropolis', 'National Museum of Tarquinia'], None),
'ninfa': ('Garden of Ninfa and Sermoneta', 'The "most romantic garden in the world" among the ruins of a medieval town. Open only on some days, by booking.', ['Garden of Ninfa', 'Sermoneta village'], 'Seasonal opening, April to November'),
'sperlonga': (None, 'A white village above the sea with some of the best beaches in Lazio. Ideal in summer.', ['white village', 'beach', 'Grotto of Tiberius'], 'Recommended June to September'),
'viterbo': (None, 'The medieval city of the popes, with intact districts and free hot springs to bathe in.', ['Palace of the Popes', 'San Pellegrino quarter', 'Underground Viterbo', 'hot springs'], None),
'bracciano': ('Lake and Castle of Bracciano', 'A medieval castle on a volcanic lake, with a lakeside walk and a lake-fish lunch.', ['Orsini-Odescalchi Castle', 'lakefront'], None),
'subiaco': ('Subiaco: monasteries of St Benedict', 'Monasteries clinging to the rock where St Benedict founded his order.', ['Sacro Speco', 'Monastery of St Scholastica'], None),
'montecassino': ('Montecassino Abbey', "St Benedict's abbey, destroyed and rebuilt after the 1944 battle.", ['Abbey', 'Polish war cemetery'], None),
'mare_ostia': ('Seaside at Ostia', "The Romans' beach, reachable with a city transport ticket. Summer only.", ['beach'], None),
}
S = {
'trastevere': (None, 'The heart of the Roman evening: aperitivo in Piazza San Calisto, dinner in a trattoria, then the steps of Piazza Trilussa.'),
'monti': ('Monti district', 'Aperitivo in Piazza Madonna dei Monti among locals and tourists, then dinner around Via Panisperna.'),
'campo_navona': ("Campo de' Fiori and Navona", "Wine bars in Via del Governo Vecchio and Piazza del Fico, dinner near Navona, the evening in Campo de' Fiori."),
'ghetto': ('Jewish Ghetto', 'Roman-Jewish dinner: Jewish-style artichokes and fried cod fillets between Portico d\'Ottavia and Via del Portico.'),
'testaccio': (None, 'The most genuine Roman cooking, from oxtail stew to cacio e pepe; then bars until late.'),
'pigneto': (None, 'An alternative pedestrian area, natural wines and craft beers. Close to our properties.'),
'tridente': ('Spanish Steps and Piazza del Popolo', 'Elegant aperitivo and terraces with a view between Via Margutta and Piazza del Popolo.'),
'prati': (None, 'Refined aperitivo bars and quiet restaurants, perfect after a day at the Vatican.'),
'san_lorenzo': (None, 'The university district: cheap, lively, full of trattorias and pubs. A short walk from home.'),
'ostiense': (None, 'A former industrial area with bars, restaurants and clubs; Eataly for those who want everything in one place.'),
'ponte_milvio': (None, "Young Romans' aperitivo spot, with the bridge of padlocks."),
'piazza_bologna': ('Piazza Bologna area (near home)', 'For a quiet evening near our properties: you will find our recommended places in the Eat section.'),
}
