# Español. A: id -> (nombre o None, desc, nombre_fuera o None, desc_fuera o None)
A = {
'illusioni': ('Museo de las Ilusiones', 'Más de 70 ilusiones ópticas y salas interactivas: divertido para todas las edades.', None, None),
'cappuccini': ('Cripta de los Capuchinos', 'Capillas decoradas con los huesos de miles de frailes: macabra y única en el mundo.', None, None),
'montemartini': (None, 'Estatuas romanas expuestas entre las turbinas de una antigua central eléctrica.', None, None),
'serra_moresca': ('Invernadero Morisco de Villa Torlonia', 'Invernadero del siglo XIX de estilo Alhambra, con vidrieras de colores. Cerrado en julio y agosto.', None, None),
'museo_luce': ('Museo de la Luz', 'La física de la luz contada con instalaciones para tocar.', None, None),
'welcome_rome': (None, 'Viaje multimedia por los 2700 años de la ciudad, ideal como introducción.', None, None),
'barracco': ('Museo Barracco', 'Pequeña colección de escultura egipcia, asiria, griega y romana.', None, None),
'museo_mura': ('Museo de las Murallas', 'Se camina dentro de la Porta San Sebastiano y a lo largo de las Murallas Aurelianas.', None, None),
'lab_mente': ('Museo Laboratorio de la Mente', 'En el antiguo manicomio de Santa Maria della Pietà: conmovedor y poco conocido.', None, None),
'anime_purgatorio': ('Museo de las Almas del Purgatorio', 'Minúscula colección de "huellas del más allá" dentro de una iglesia neogótica.', None, None),
'buco_serratura': ('Ojo de la cerradura del Aventino', 'San Pedro enmarcado en la cerradura de los Caballeros de Malta.', None, None),
'coppede': ('Barrio Coppedè', 'Arquitectura de cuento entre modernismo, gótico y medieval.', None, None),
'palazzo_valentini': ('Domus romanas del Palazzo Valentini', 'Casas romanas bajo un palacio, reanimadas con proyecciones multimedia.', None, None),
'case_celio': ('Casas romanas del Celio', 'Viviendas romanas con frescos bajo una basílica.', None, None),
'galleria_spada': (None, 'Famosa por la falsa perspectiva de Borromini: 9 metros que parecen 35.', None, None),
'galleria_sciarra': (None, 'Patio modernista con frescos, escondido a dos pasos de la Via del Corso.', None, None),
'maxxi': (None, 'Arte contemporáneo en el edificio diseñado por Zaha Hadid.', None, None),
'dreamers': (None, 'Salas inmersivas y coloridas, pensadas para las fotos.', None, None),
'ikono': (None, 'Experiencia sensorial en salas temáticas.', None, None),
'time_elevator': (None, 'Cine 5D con asientos móviles sobre la historia de Roma, ideal para niños.', None, None),
'colosseo': ('Coliseo, Foro Romano y Palatino', 'El símbolo de Roma y el corazón de la ciudad antigua, con una sola entrada.', 'Coliseo (desde fuera)', 'El Coliseo desde fuera, con el Arco de Constantino y la vista del Foro. Entrada no incluida.'),
'pantheon': ('Panteón', 'El templo romano mejor conservado, con la mayor cúpula de hormigón jamás construida.', 'Panteón (desde fuera)', 'La fachada del Panteón y la Piazza della Rotonda con su fuente. Entrada no incluida.'),
'trevi': ('Fontana di Trevi', 'La fuente más famosa del mundo. Vista libre desde la plaza, 2€ para bajar junto al agua.', None, None),
'navona': (None, 'Plaza barroca con la Fuente de los Cuatro Ríos de Bernini.', None, None),
'spagna': ('Plaza de España y Trinità dei Monti', 'La escalinata más famosa de Roma, con la Barcaccia a sus pies.', None, None),
'capitolini': ('Museos Capitolinos y Piazza del Campidoglio', 'El museo público más antiguo del mundo, en la plaza diseñada por Miguel Ángel.', 'Piazza del Campidoglio y terraza sobre el Foro', 'La Piazza del Campidoglio de Miguel Ángel y la terraza gratuita sobre el Foro Romano.'),
'castel_santangelo': ('Castillo de Sant\'Angelo', 'De mausoleo de Adriano a fortaleza de los papas, con terraza panorámica.', "Castillo de Sant'Angelo (desde fuera)", 'El castillo visto desde el Puente de los Ángeles y el Tíber. Entrada no incluida.'),
'vittoriano': (None, 'Monumento imponente de entrada libre; la terraza panorámica cuesta 18€.', None, None),
'fori_imperiali': (None, 'Paseo junto a los foros de César, Augusto y Trajano, visibles desde la calle.', None, None),
'ghetto': ("Gueto judío y Pórtico de Octavia", 'El barrio judío más antiguo de Europa, entre ruinas romanas y alcachofas a la judía.', None, None),
'popolo': (None, 'Gran plaza neoclásica con el obelisco y las iglesias gemelas.', None, None),
'campo_fiori': (None, 'Mercado por la mañana, vida nocturna por la noche, con la estatua de Giordano Bruno.', None, None),
'bocca_verita': ('Boca de la Verdad', 'La legendaria máscara que muerde la mano de los mentirosos.', 'Boca de la Verdad (desde el pórtico)', 'La Boca de la Verdad se ve desde la verja del pórtico, incluso sin entrar.'),
'torre_argentina': (None, 'El área sagrada donde fue asesinado César, hoy también colonia de gatos.', None, None),
'teatro_marcello': ('Teatro de Marcelo', 'Teatro romano sobre el que se construyó un palacio habitado.', None, None),
'isola_tiberina': ('Isla Tiberina', 'La única isla del Tíber, unida por el puente romano más antiguo aún en uso.', None, None),
'circo_massimo': ('Circo Máximo', 'El mayor estadio de la Antigüedad, hoy un gran prado.', None, None),
'ara_pacis': (None, 'El altar de Augusto en el pabellón de Richard Meier.', 'Ara Pacis (desde fuera)', 'El altar de Augusto visto a través del pabellón de cristal de Richard Meier.'),
'musei_vaticani': ('Museos Vaticanos y Capilla Sixtina', 'Una de las mayores colecciones del mundo, hasta el Juicio Final de Miguel Ángel. Online sin colas 25€.', None, None),
'san_pietro': ('Basílica de San Pedro', 'La iglesia más grande de la cristiandad, con la Piedad de Miguel Ángel.', None, None),
'piazza_san_pietro': ('Plaza de San Pedro', 'La columnata de Bernini abraza a los fieles.', None, None),
'cupola': ('Cúpula de San Pedro', 'Ascensor más 320 escalones (10€) o 551 escalones a pie (8€) hasta la vista más famosa de Roma.', None, None),
'grotte_vaticane': ('Grutas Vaticanas', 'Las tumbas de los papas bajo la basílica.', None, None),
'necropoli': ('Necrópolis Vaticana (Scavi)', 'Visita guiada a la tumba de San Pedro: reserva con mucha antelación.', None, None),
'giardini_vaticani': ('Jardines Vaticanos', 'Visita guiada a los jardines de los papas, solo con reserva. Desde 20€, 40€ con el bus panorámico.', None, None),
'ponte_santangelo': ("Puente de Sant'Angelo", 'El puente de los ángeles de Bernini, frente al castillo.', None, None),
'borgo_pio': ('Borgo Pio y Passetto di Borgo', 'Callejuelas bajo el pasadizo secreto que llevaba a los papas al castillo.', None, None),
'prati': ('Prati y Via Cola di Rienzo', 'Barrio elegante de finales del XIX, ideal para ir de compras.', None, None),
'palazzaccio': ('Palacio de Justicia', 'El "Palazzaccio", monumental y controvertido.', None, None),
'laterano': ('San Juan de Letrán', 'La catedral de Roma, madre de todas las iglesias del mundo.', None, None),
'santa_maria_maggiore': ('Santa María la Mayor', 'Mosaicos del siglo V y techo dorado con el primer oro de América.', None, None),
'san_paolo': ('San Pablo Extramuros', 'Basílica inmensa con los retratos de todos los papas y un claustro espléndido.', None, None),
'vincoli': ('San Pedro encadenado', 'El Moisés de Miguel Ángel y las cadenas de San Pedro.', None, None),
'san_clemente': ('San Clemente y sus subterráneos', 'Tres niveles superpuestos: iglesia medieval, basílica del siglo IV y templo de Mitra. Excavaciones con reserva.', None, None),
'santa_maria_trastevere': (None, 'Una de las iglesias más antiguas de Roma, con mosaicos dorados en la fachada y el ábside.', None, None),
'san_luigi': (None, 'Tres obras maestras de Caravaggio sobre la vida de San Mateo, gratis.', None, None),
'sant_ignazio': ("San Ignacio", 'La falsa cúpula pintada de Andrea Pozzo: un espejo en el centro revela el engaño.', None, None),
'santa_maria_popolo': (None, 'Dos Caravaggio y la Capilla Chigi de Rafael y Bernini.', None, None),
'gesu': ('Iglesia del Gesù', 'Obra maestra barroca de los jesuitas; cada día a las 17:30 la "máquina" del altar de San Ignacio.', None, None),
'minerva': (None, 'La única iglesia gótica de Roma, con el elefantito de Bernini delante.', None, None),
'scala_santa': ('Escalera Santa', 'La escalera que Jesús habría subido ante Pilato: los fieles la suben de rodillas.', None, None),
'vittoria': (None, 'El Éxtasis de Santa Teresa, obra maestra de Bernini.', None, None),
'sant_agostino': ('San Agustín', 'La Virgen de los Peregrinos de Caravaggio.', None, None),
'aracoeli': (None, 'Se llega subiendo 124 escalones; dentro, frescos de Pinturicchio.', None, None),
'santa_cecilia': (None, 'La estatua de la santa esculpida tal como fue hallada y un raro fresco de Cavallini.', None, None),
'santa_prassede': (None, 'La capilla de San Zenón, cubierta por completo de mosaicos dorados.', None, None),
'quattro_fontane': (None, 'La obra maestra de Borromini: una cúpula oval del tamaño de un pilar de San Pedro.', None, None),
'sant_andrea_quirinale': ("Sant'Andrea al Quirinale", 'La "perla" de Bernini, a cien metros de la de su rival Borromini.', None, None),
'santo_stefano_rotondo': (None, 'Iglesia circular del siglo V, con crudos frescos de mártires.', None, None),
'quattro_coronati': (None, 'Monasterio fortificado con la capilla de San Silvestre y un claustro escondido.', None, None),
'santa_sabina': (None, 'Basílica del siglo V con su puerta de madera original y el Jardín de los Naranjos al lado.', None, None),
'tempietto_bramante': ('Templete de Bramante', 'La joya del Renacimiento, donde según la tradición fue crucificado Pedro.', None, None),
'santa_maria_angeli': (None, 'Miguel Ángel convirtió las Termas de Diocleciano en iglesia; en el suelo, una meridiana.', None, None),
'sant_ivo': ("Sant'Ivo alla Sapienza", 'La cúpula en espiral de Borromini; normalmente abierta solo el domingo por la mañana.', None, None),
'san_lorenzo': ('San Lorenzo Extramuros', 'Basílica medieval con claustro, junto al cementerio del Verano.', None, None),
'santa_costanza': ('Mausoleo de Santa Constanza', 'Mausoleo del siglo IV con mosaicos de vendimia aún paganos.', None, None),
'chiostro_bramante': ('Claustro de Bramante', 'Claustro renacentista con exposiciones temporales y cafetería con vistas a Santa Maria della Pace.', None, None),
'cosma_damiano': ('Santos Cosme y Damián', 'Mosaico del ábside del siglo VI y un gran belén napolitano del XVIII.', None, None),
'galleria_borghese': ('Galería Borghese', 'Bernini y Caravaggio en una villa barroca. Reserva obligatoria, turnos de 2 horas.', None, None),
'villa_borghese': (None, 'El parque más famoso de Roma: paseos, lago con barcas, alquiler de bicis y rickshaws.', None, None),
'pincio': ('Terraza del Pincio', 'Vista de la Piazza del Popolo y las cúpulas, espléndida al atardecer.', None, None),
'giardino_aranci': ('Jardín de los Naranjos', 'El atardecer más romántico de Roma, entre naranjos sobre el Tíber.', None, None),
'gianicolo': ('Mirador del Gianicolo', 'La terraza más amplia sobre la ciudad; a mediodía dispara un cañonazo.', None, None),
'fontanone': ('Fontanone del Gianicolo', 'La fuente monumental del Acqua Paola, con vistas al Trastevere.', None, None),
'terrazza_caffarelli': ('Terraza Caffarelli', 'Terraza en el Capitolio con vistas a los tejados y al Vittoriano.', None, None),
'parco_acquedotti': ('Parque de los Acueductos', 'Arcos de acueductos romanos entre prados: la Roma de "La gran belleza".', None, None),
'appia_antica': ('Vía Apia Antigua', 'La "reina de las calzadas": losas romanas, tumbas y campo, a pie o en bici.', None, None),
'villa_doria_pamphilj': (None, 'El parque más grande de Roma, querido por los romanos para correr y hacer picnic.', None, None),
'villa_torlonia': (None, 'La villa de Mussolini: parque gratuito, Casina delle Civette modernista a 10,50€.', None, None),
'roseto': ('Rosaleda Municipal', 'Más de mil variedades de rosas, abierta solo en primavera.', None, None),
'villa_celimontana': (None, 'Parque tranquilo a dos pasos del Coliseo, con un obelisco egipcio.', None, None),
'villa_sciarra': (None, 'Pequeño jardín romántico con fuentes y estatuas, casi desconocido para los turistas.', None, None),
'villa_ada': (None, 'Gran parque natural con lago, antigua residencia real.', None, None),
'caffarella': ('Parque de la Caffarella', 'Campiña romana en la ciudad: granjas, ninfeos y ruinas.', None, None),
'orto_botanico': ('Jardín Botánico', 'Jardín botánico a los pies del Gianicolo, con invernaderos y bambú.', None, None),
'bioparco': (None, 'El zoo de Roma, ideal para quien viaja con niños.', None, None),
'villa_medici': (None, 'Sede de la Academia de Francia: jardines renacentistas con visita guiada.', None, None),
'zodiaco': ('Mirador del Zodiaco', 'El punto más alto de Roma, lejos del centro: se llega en autobús o taxi.', None, None),
'domus_aurea': (None, 'El palacio enterrado de Nerón, con gafas de realidad virtual que muestran las salas como eran. Grupos pequeños, reservar pronto.', None, None),
'colosseo_sotterranei': ('Coliseo: arena y subterráneos', 'Visita especial por donde pasaban gladiadores y fieras, con acceso a la arena.', None, None),
'caracalla': ('Termas de Caracalla', 'Las termas más imponentes de la Antigüedad, menos concurridas que el Foro. En verano, ópera.', 'Termas de Caracalla (desde fuera)', 'Las imponentes ruinas de las termas vistas desde la avenida. Entrada no incluida.'),
'ostia_antica': (None, 'Una Pompeya a 30 minutos en tren: calles, tabernas, teatro y casas intactas.', None, None),
'palazzo_massimo': ('Museo Nacional Romano – Palazzo Massimo', 'Frescos de la villa de Livia, el Púgil en reposo y mosaicos extraordinarios.', None, None),
'terme_diocleziano': ('Termas de Diocleciano', 'Enormes termas romanas con un claustro de Miguel Ángel.', None, None),
'palazzo_altemps': (None, 'Escultura antigua en un palacio renacentista, incluido el Trono Ludovisi.', None, None),
'crypta_balbi': (None, 'Cómo cambió Roma de la Antigüedad a la Edad Media, capa tras capa.', None, None),
'mercati_traiano': ('Mercados de Trajano', 'El "centro comercial" de la Roma antigua, con vistas desde lo alto a los Foros.', None, None),
'carcere_mamertino': ('Cárcel Mamertina', 'La prisión donde, según la tradición, estuvo encerrado San Pedro.', None, None),
'stadio_domiziano': ('Estadio de Domiciano', 'El estadio romano escondido bajo la Piazza Navona, que explica su forma.', None, None),
'vicus_caprarius': ('Vicus Caprarius – Ciudad del Agua', 'Bajo Trevi, una antigua casa romana atravesada por el agua que alimenta la fuente.', None, None),
'mausoleo_augusto': ('Mausoleo de Augusto', 'La tumba circular del primer emperador, reabierta tras décadas de restauración.', 'Mausoleo de Augusto (desde fuera)', 'La tumba circular de Augusto vista desde la plaza.'),
'san_callisto': ('Catacumbas de San Calixto', 'Las catacumbas más grandes y famosas, con la cripta de los papas. Visita guiada incluida.', None, None),
'domitilla': ('Catacumbas de Domitila', 'Catacumbas con una basílica subterránea y frescos paleocristianos. Visita guiada incluida.', None, None),
'san_sebastiano': ('Catacumbas de San Sebastián', 'Catacumbas con mausoleos romanos perfectamente conservados.', None, None),
'priscilla': ('Catacumbas de Priscila', 'La representación más antigua conocida de la Virgen. Cerca de nuestros alojamientos.', None, None),
'cecilia_metella': ('Tumba de Cecilia Metela', 'El mausoleo-fortaleza símbolo de la Vía Apia.', None, None),
'villa_quintili': ('Villa de los Quintilios', 'Enorme villa imperial casi desierta, fuera de los circuitos turísticos.', None, None),
'cimitero_acattolico': ('Cementerio Acatólico y Pirámide Cestia', 'El cementerio romántico de Keats y Shelley, a la sombra de una pirámide romana.', None, None),
'monte_testaccio': ('Monte Testaccio (de los tiestos)', 'Una colina hecha de ánforas rotas: el vertedero de la Roma antigua. Solo con visitas guiadas ocasionales.', None, None),
'trastevere': (None, 'Callejuelas empedradas, hiedra y trattorias: el barrio más romano de Roma, en su mejor momento por la noche.', None, None),
'monti': ('Barrio de Monti', 'El barrio más antiguo, hoy lleno de tiendas vintage, artesanos y placitas.', None, None),
'testaccio': ('Testaccio y su mercado', 'El barrio de la auténtica cocina romana, con su mercado cubierto y comida callejera.', None, None),
'via_margutta': (None, 'La calle de los artistas y de "Vacaciones en Roma", con talleres y galerías.', None, None),
'piazza_mattei': ('Fuente de las Tortugas', 'Pequeña fuente renacentista en una placita escondida del Gueto.', None, None),
'garbatella': (None, 'Ciudad jardín de los años 20: casitas, patios y viviendas populares de postal.', None, None),
'pigneto': (None, 'El barrio de Pasolini, hoy murales, bares y vida nocturna alternativa.', None, None),
'via_giulia': (None, 'Calle renacentista recta como una flecha, con palacios nobles y el arco Farnese.', None, None),
'piazza_farnese': (None, 'Plaza elegante con el palacio de Miguel Ángel, hoy embajada de Francia.', None, None),
'via_coronari': (None, 'La calle de los anticuarios, a dos pasos de Piazza Navona.', None, None),
'san_lorenzo_quartiere': ('Barrio de San Lorenzo', 'El barrio universitario, murales y bares. A pocos pasos de nuestros alojamientos.', None, None),
'eur': (None, 'La ciudad racionalista creada para la Exposición de 1942, con el "Coliseo cuadrado".', None, None),
'ostiense_street_art': ('Ostiense y el Gasómetro', 'Arqueología industrial y grandes murales, del Gasómetro a los antiguos Mercados Generales.', None, None),
'tor_marancia': (None, 'Veintidós edificios populares pintados por artistas urbanos internacionales.', None, None),
'governo_vecchio': (None, 'Tiendas vintage y talleres entre Navona y Chiesa Nuova.', None, None),
'quadraro': ('Quadraro y el MURo', 'Museo de arte urbano al aire libre en un barrio popular de la Resistencia.', None, None),
'porta_portese': ('Mercado de Porta Portese', 'El mercadillo más famoso de Roma: solo el domingo por la mañana.', None, None),
'mercato_centrale': ('Mercato Centrale de Termini', 'Mercado gastronómico con los mejores artesanos del sabor bajo el mismo techo.', None, None),
'mercato_trionfale': ('Mercado Trionfale', 'El mercado cubierto de los romanos, a dos pasos de los Museos Vaticanos.', None, None),
'campagna_amica': ('Mercado Campagna Amica en el Circo Máximo', 'Productos de los agricultores del Lacio, sábados y domingos.', None, None),
'cooking_class': ('Clase de cocina romana', 'Aprendes a hacer pasta fresca, tiramisú o pizza y luego te comes lo que has cocinado. Normalmente 60-90€.', None, None),
'food_tour': ('Food tour por Trastevere o Testaccio', 'Degustaciones guiadas de supplì, pizza al corte, quesos y helado. Normalmente 60-90€.', None, None),
'vespa_tour': ('Tour en Vespa o en Fiat 500 de época', 'Roma como en "Vacaciones en Roma", con conductor o al volante. Normalmente 80-150€.', None, None),
'golf_cart': ('Tour en carrito de golf', 'El centro histórico sin esfuerzo: ideal para quien camina poco.', None, None),
'bici_appia': ('Vía Apia en bicicleta', 'Alquiler de bicis en el Appia Info Point y a pedalear entre tumbas y losas romanas.', None, None),
'crociera_tevere': ('Barco por el Tíber', 'Roma vista desde el río, también con cena a bordo.', None, None),
'cinecitta': (None, 'Visita a los estudios de Fellini y a los decorados de la Roma antigua.', None, None),
'explora': ('Explora – Museo de los Niños', 'Museo interactivo donde los niños lo hacen todo ellos solos.', None, None),
'opera_caracalla': ('Ópera en las Termas de Caracalla', 'Ópera y ballet al aire libre entre las ruinas de las termas. Solo en verano.', None, None),
}
G = {
'tivoli': ("Tívoli: Villa d'Este y Villa Adriana", 'Dos sitios UNESCO en un día: la villa del emperador Adriano y el jardín de las cien fuentes.', ['Villa Adriana', "Villa d'Este", 'centro de Tívoli'], 'Cerrado el lunes por la mañana'),
'pompei': ('Pompeya', 'La ciudad sepultada por el Vesubio. Frecciarossa hasta Nápoles y luego Circumvesuviana: día largo pero inolvidable.', ['Excavaciones de Pompeya'], None),
'firenze': ('Florencia en un día', 'En Frecciarossa se llega en hora y media: lo mejor del Renacimiento en un día.', ['Duomo', 'Ponte Vecchio', 'Piazza della Signoria', 'Uffizi (opcional)'], None),
'orvieto': (None, 'Ciudad etrusca sobre una roca de toba, con una de las catedrales góticas más bellas de Italia y un laberinto de cuevas.', ['Duomo', 'Pozo de San Patricio', 'Orvieto subterránea'], None),
'napoli': ('Nápoles en un día', 'Una hora y diez de Frecciarossa hasta la ciudad más viva de Italia, y su pizza.', ['centro histórico', 'Cristo Velado', 'paseo marítimo', 'pizza'], None),
'castelli': ('Castelli Romani', 'Pueblos en colinas volcánicas: vino de Frascati, porchetta de Ariccia, fresitas de Nemi y el palacio de los papas.', ['Frascati', 'Castel Gandolfo', 'Ariccia', 'Nemi'], 'El Palacio Papal de Castel Gandolfo es de pago'),
'tuscia': ('Civita di Bagnoregio y el Parque de los Monstruos', '"La ciudad que muere" sobre su espolón de toba y el jardín de esculturas monstruosas que fascinó a Dalí. Se necesita coche.', ['Civita di Bagnoregio', 'Bosque Sagrado de Bomarzo'], None),
'assisi': ('Asís', 'La ciudad de San Francisco, con la basílica pintada al fresco por Giotto.', ['Basílica de San Francisco', 'centro histórico'], None),
'cerveteri': ('Cerveteri: necrópolis etrusca', 'Una ciudad de los muertos etrusca, patrimonio UNESCO, con tumbas en forma de casa. Cerca está el mar de Ladispoli.', ['Necrópolis de la Banditaccia', 'Museo Cerite'], None),
'tarquinia': ('Tarquinia: tumbas pintadas', 'Las tumbas etruscas con frescos más bellas del mundo, con colores aún vivos tras 2500 años.', ['Necrópolis de Monterozzi', 'Museo Nacional Tarquiniense'], None),
'ninfa': ('Jardín de Ninfa y Sermoneta', 'El "jardín más romántico del mundo" entre las ruinas de una ciudad medieval. Abierto solo algunos días, con reserva.', ['Jardín de Ninfa', 'pueblo de Sermoneta'], 'Apertura de temporada, de abril a noviembre'),
'sperlonga': (None, 'Pueblo blanco sobre el mar y algunas de las mejores playas del Lacio. Ideal en verano.', ['pueblo blanco', 'playa', 'Gruta de Tiberio'], 'Recomendada de junio a septiembre'),
'viterbo': (None, 'La ciudad medieval de los papas, con barrios intactos y termas libres donde bañarse.', ['Palacio de los Papas', 'barrio de San Pellegrino', 'Viterbo subterránea', 'termas'], None),
'bracciano': ('Lago y Castillo de Bracciano', 'Castillo medieval sobre un lago volcánico, con paseo y comida de pescado de lago.', ['Castillo Orsini-Odescalchi', 'paseo del lago'], None),
'subiaco': ('Subiaco: monasterios de San Benito', 'Monasterios aferrados a la roca donde San Benito fundó su orden.', ['Sacro Speco', 'Monasterio de Santa Escolástica'], None),
'montecassino': ('Abadía de Montecassino', 'La abadía de San Benito, destruida y reconstruida tras la batalla de 1944.', ['Abadía', 'cementerio militar polaco'], None),
'mare_ostia': ('Playa de Ostia', 'La playa de los romanos, con el billete de transporte urbano. Solo en verano.', ['playa'], None),
}
S = {
'trastevere': (None, 'El corazón de la noche romana: aperitivo en Piazza San Calisto, cena en trattoria y luego las escaleras de Piazza Trilussa.'),
'monti': ('Barrio de Monti', 'Aperitivo en Piazza Madonna dei Monti entre romanos y turistas, luego cena por la zona de Via Panisperna.'),
'campo_navona': ("Campo de' Fiori y Navona", "Vinotecas en Via del Governo Vecchio y Piazza del Fico, cena cerca de Navona, noche en Campo de' Fiori."),
'ghetto': ('Gueto judío', 'Cena judeo-romana: alcachofas a la judía y filetes de bacalao entre el Pórtico de Octavia y Via del Portico.'),
'testaccio': (None, 'La cocina romana más auténtica, del rabo de buey a la cacio e pepe; luego bares hasta tarde.'),
'pigneto': (None, 'Zona peatonal alternativa, vinos naturales y cervezas artesanas. Cerca de nuestros alojamientos.'),
'tridente': ('Plaza de España y Piazza del Popolo', 'Aperitivo elegante y terrazas con vistas entre Via Margutta y Piazza del Popolo.'),
'prati': (None, 'Aperitivos refinados y restaurantes tranquilos, perfectos tras un día en el Vaticano.'),
'san_lorenzo': (None, 'El barrio universitario: barato, animado, lleno de trattorias y pubs. A dos pasos de casa.'),
'ostiense': (None, 'Antigua zona industrial con bares, restaurantes y clubes; Eataly para quien lo quiere todo en un sitio.'),
'ponte_milvio': (None, 'El aperitivo de los jóvenes romanos, con el puente de los candados.'),
'piazza_bologna': ('Zona de Piazza Bologna (cerca de casa)', 'Para una noche tranquila cerca de nuestros alojamientos: encontrarás los locales recomendados en la sección Comer.'),
}
