# Français. A: id -> (nom ou None, desc, nom_dehors ou None, desc_dehors ou None)
A = {
'illusioni': ('Musée des Illusions', "Plus de 70 illusions d'optique et salles interactives : amusant à tout âge.", None, None),
'cappuccini': ('Crypte des Capucins', 'Chapelles décorées avec les os de milliers de frères : macabre et unique au monde.', None, None),
'montemartini': (None, "Statues romaines exposées parmi les turbines d'une ancienne centrale électrique.", None, None),
'serra_moresca': ('Serre mauresque de la Villa Torlonia', 'Serre du XIXe siècle de style Alhambra, avec vitraux colorés. Fermée en juillet et août.', None, None),
'museo_luce': ('Musée de la Lumière', 'La physique de la lumière racontée par des installations à toucher.', None, None),
'welcome_rome': (None, 'Voyage multimédia dans les 2700 ans de la ville, idéal pour commencer.', None, None),
'barracco': ('Musée Barracco', 'Petite collection de sculptures égyptiennes, assyriennes, grecques et romaines.', None, None),
'museo_mura': ('Musée des Murailles', "On marche à l'intérieur de la Porta San Sebastiano et le long des murailles d'Aurélien.", None, None),
'lab_mente': ("Musée Laboratoire de l'Esprit", "Dans l'ancien asile de Santa Maria della Pietà : émouvant et peu connu.", None, None),
'anime_purgatorio': ('Musée des Âmes du Purgatoire', "Minuscule collection d'« empreintes de l'au-delà » dans une église néogothique.", None, None),
'buco_serratura': ("Trou de serrure de l'Aventin", 'Saint-Pierre encadré dans la serrure des Chevaliers de Malte.', None, None),
'coppede': ('Quartier Coppedè', 'Une architecture de conte de fées entre Art nouveau, gothique et médiéval.', None, None),
'palazzo_valentini': ('Domus romaines du Palazzo Valentini', 'Maisons romaines sous un palais, ranimées par des projections multimédias.', None, None),
'case_celio': ('Maisons romaines du Celio', 'Habitations romaines ornées de fresques sous une basilique.', None, None),
'galleria_spada': (None, 'Célèbre pour la fausse perspective de Borromini : 9 mètres qui en paraissent 35.', None, None),
'galleria_sciarra': (None, 'Cour Art nouveau à fresques, cachée à deux pas de la Via del Corso.', None, None),
'maxxi': (None, 'Art contemporain dans le bâtiment conçu par Zaha Hadid.', None, None),
'dreamers': (None, 'Salles immersives et colorées, pensées pour les photos.', None, None),
'ikono': (None, 'Expérience sensorielle en salles thématiques.', None, None),
'time_elevator': (None, "Cinéma 5D à sièges mobiles sur l'histoire de Rome, idéal pour les enfants.", None, None),
'colosseo': ('Colisée, Forum romain et Palatin', "Le symbole de Rome et le cœur de la ville antique, avec un seul billet.", 'Colisée (de l\'extérieur)', "Le Colisée de l'extérieur, avec l'arc de Constantin et la vue sur le Forum. Entrée non comprise."),
'pantheon': ('Panthéon', 'Le temple romain le mieux conservé, avec la plus grande coupole en béton jamais construite.', "Panthéon (de l'extérieur)", 'La façade du Panthéon et la Piazza della Rotonda avec sa fontaine. Entrée non comprise.'),
'trevi': ('Fontaine de Trevi', "La fontaine la plus célèbre du monde. Vue libre depuis la place, 2 € pour descendre près de l'eau.", None, None),
'navona': (None, 'Place baroque avec la fontaine des Quatre-Fleuves du Bernin.', None, None),
'spagna': ("Place d'Espagne et Trinité-des-Monts", "L'escalier le plus célèbre de Rome, avec la Barcaccia à ses pieds.", None, None),
'capitolini': ('Musées du Capitole et Piazza del Campidoglio', 'Le plus ancien musée public du monde, sur la place dessinée par Michel-Ange.', 'Piazza del Campidoglio et terrasse sur le Forum', 'La place du Capitole de Michel-Ange et la terrasse gratuite sur le Forum romain.'),
'castel_santangelo': ('Château Saint-Ange', "Du mausolée d'Hadrien à la forteresse des papes, avec terrasse panoramique.", "Château Saint-Ange (de l'extérieur)", 'Le château vu du pont des Anges et des quais du Tibre. Entrée non comprise.'),
'vittoriano': (None, "Monument imposant en accès libre ; la terrasse panoramique coûte 18 €.", None, None),
'fori_imperiali': (None, "Promenade le long des forums de César, d'Auguste et de Trajan, visibles depuis la rue.", None, None),
'ghetto': ("Ghetto juif et Portique d'Octavie", "Le plus ancien quartier juif d'Europe, entre ruines romaines et artichauts à la juive.", None, None),
'popolo': (None, "Grande place néoclassique avec l'obélisque et les églises jumelles.", None, None),
'campo_fiori': (None, 'Marché le matin, vie nocturne le soir, avec la statue de Giordano Bruno.', None, None),
'bocca_verita': ('Bouche de la Vérité', 'Le masque légendaire qui mord la main des menteurs.', 'Bouche de la Vérité (depuis le portique)', "On voit la Bouche de la Vérité depuis la grille du portique, même sans entrer."),
'torre_argentina': (None, "L'aire sacrée où César fut assassiné, aujourd'hui aussi refuge pour chats.", None, None),
'teatro_marcello': ('Théâtre de Marcellus', 'Théâtre romain sur lequel on a bâti un palais habité.', None, None),
'isola_tiberina': ('Île Tibérine', "L'unique île du Tibre, reliée par le plus ancien pont romain encore en usage.", None, None),
'circo_massimo': ('Circus Maximus', "Le plus grand stade de l'Antiquité, aujourd'hui une grande pelouse.", None, None),
'ara_pacis': (None, "L'autel d'Auguste dans le pavillon de Richard Meier.", "Ara Pacis (de l'extérieur)", "L'autel d'Auguste vu à travers le pavillon de verre de Richard Meier."),
'musei_vaticani': ('Musées du Vatican et chapelle Sixtine', "L'une des plus grandes collections au monde, jusqu'au Jugement dernier de Michel-Ange. Coupe-file en ligne 25 €.", None, None),
'san_pietro': ('Basilique Saint-Pierre', 'La plus grande église de la chrétienté, avec la Pietà de Michel-Ange.', None, None),
'piazza_san_pietro': ('Place Saint-Pierre', 'La colonnade du Bernin embrasse les fidèles.', None, None),
'cupola': ('Coupole de Saint-Pierre', "Ascenseur plus 320 marches (10 €) ou 551 marches à pied (8 €) jusqu'à la vue la plus célèbre de Rome.", None, None),
'grotte_vaticane': ('Grottes vaticanes', 'Les tombeaux des papes sous la basilique.', None, None),
'necropoli': ('Nécropole vaticane (Scavi)', "Visite guidée du tombeau de saint Pierre : réserver longtemps à l'avance.", None, None),
'giardini_vaticani': ('Jardins du Vatican', 'Visite guidée des jardins des papes, sur réservation uniquement. Dès 20 €, 40 € en bus panoramique.', None, None),
'ponte_santangelo': ('Pont Saint-Ange', 'Le pont des anges du Bernin, face au château.', None, None),
'borgo_pio': ('Borgo Pio et Passetto di Borgo', 'Ruelles sous le couloir secret qui menait les papes au château.', None, None),
'prati': ('Prati et Via Cola di Rienzo', 'Quartier élégant de la fin du XIXe siècle, idéal pour le shopping.', None, None),
'palazzaccio': ('Palais de Justice', 'Le « Palazzaccio », monumental et controversé.', None, None),
'laterano': ('Saint-Jean-de-Latran', 'La cathédrale de Rome, mère de toutes les églises du monde.', None, None),
'santa_maria_maggiore': ('Sainte-Marie-Majeure', "Mosaïques du Ve siècle et plafond doré avec le premier or des Amériques.", None, None),
'san_paolo': ('Saint-Paul-hors-les-Murs', 'Immense basilique avec les portraits de tous les papes et un cloître splendide.', None, None),
'vincoli': ('Saint-Pierre-aux-Liens', 'Le Moïse de Michel-Ange et les chaînes de saint Pierre.', None, None),
'san_clemente': ('Saint-Clément et ses souterrains', 'Trois niveaux superposés : église médiévale, basilique du IVe siècle et temple de Mithra. Fouilles sur réservation.', None, None),
'santa_maria_trastevere': ('Sainte-Marie-du-Trastevere', "L'une des plus anciennes églises de Rome, avec des mosaïques d'or sur la façade et l'abside.", None, None),
'san_luigi': ('Saint-Louis-des-Français', 'Trois chefs-d’œuvre du Caravage sur la vie de saint Matthieu, gratuits.', None, None),
'sant_ignazio': ('Saint-Ignace', "La fausse coupole peinte d'Andrea Pozzo : un miroir au centre révèle l'illusion.", None, None),
'santa_maria_popolo': ('Sainte-Marie-du-Peuple', 'Deux Caravage et la chapelle Chigi de Raphaël et du Bernin.', None, None),
'gesu': ('Église du Gesù', "Chef-d'œuvre baroque des jésuites ; chaque jour à 17h30 la « machine » de l'autel de saint Ignace.", None, None),
'minerva': ('Sainte-Marie-sur-Minerve', "La seule église gothique de Rome, avec le petit éléphant du Bernin devant.", None, None),
'scala_santa': ('Escalier saint', "L'escalier que Jésus aurait gravi devant Pilate : les fidèles le montent à genoux.", None, None),
'vittoria': ('Sainte-Marie-de-la-Victoire', "L'Extase de sainte Thérèse, chef-d'œuvre du Bernin.", None, None),
'sant_agostino': ('Saint-Augustin', 'La Madone des pèlerins du Caravage.', None, None),
'aracoeli': (None, 'On y accède en montant 124 marches ; à l’intérieur, des fresques du Pinturicchio.', None, None),
'santa_cecilia': ('Sainte-Cécile-du-Trastevere', 'La statue de la sainte sculptée telle qu’on la retrouva et une rare fresque de Cavallini.', None, None),
'santa_prassede': ('Sainte-Praxède', 'La chapelle Saint-Zénon, entièrement couverte de mosaïques d’or.', None, None),
'quattro_fontane': ('Saint-Charles-aux-Quatre-Fontaines', "Le chef-d'œuvre de Borromini : une coupole ovale grande comme un pilier de Saint-Pierre.", None, None),
'sant_andrea_quirinale': ('Saint-André-du-Quirinal', 'La « perle » du Bernin, à cent mètres de celle de son rival Borromini.', None, None),
'santo_stefano_rotondo': (None, 'Église circulaire du Ve siècle, avec de crues fresques de martyrs.', None, None),
'quattro_coronati': (None, 'Monastère fortifié avec la chapelle Saint-Sylvestre et un cloître caché.', None, None),
'santa_sabina': ('Sainte-Sabine', "Basilique du Ve siècle avec sa porte en bois d'origine et le jardin des Orangers à côté.", None, None),
'tempietto_bramante': ('Tempietto de Bramante', 'Le joyau de la Renaissance, où selon la tradition Pierre fut crucifié.', None, None),
'santa_maria_angeli': ('Sainte-Marie-des-Anges', 'Michel-Ange transforma les thermes de Dioclétien en église ; une méridienne au sol.', None, None),
'sant_ivo': ('Saint-Yves-de-la-Sapience', 'La coupole en spirale de Borromini ; en général ouverte seulement le dimanche matin.', None, None),
'san_lorenzo': ('Saint-Laurent-hors-les-Murs', 'Basilique médiévale avec cloître, à côté du cimetière du Verano.', None, None),
'santa_costanza': ('Mausolée de Sainte-Constance', 'Mausolée du IVe siècle avec des mosaïques de vendanges encore païennes.', None, None),
'chiostro_bramante': ('Cloître de Bramante', 'Cloître Renaissance accueillant des expositions, avec un café donnant sur Santa Maria della Pace.', None, None),
'cosma_damiano': ('Saints-Côme-et-Damien', "Mosaïque de l'abside du VIe siècle et une grande crèche napolitaine du XVIIIe.", None, None),
'galleria_borghese': ('Galerie Borghèse', 'Le Bernin et le Caravage dans une villa baroque. Réservation obligatoire, créneaux de 2 heures.', None, None),
'villa_borghese': (None, 'Le parc le plus célèbre de Rome : allées, lac avec barques, location de vélos et de rosalies.', None, None),
'pincio': ('Terrasse du Pincio', 'Vue sur la Piazza del Popolo et les coupoles, splendide au coucher du soleil.', None, None),
'giardino_aranci': ('Jardin des Orangers', 'Le coucher de soleil le plus romantique de Rome, parmi les orangers au-dessus du Tibre.', None, None),
'gianicolo': ('Belvédère du Janicule', 'La plus vaste terrasse sur la ville ; à midi, un coup de canon.', None, None),
'fontanone': ('Fontanone du Janicule', "La fontaine monumentale de l'Acqua Paola, avec vue sur le Trastevere.", None, None),
'terrazza_caffarelli': ('Terrasse Caffarelli', 'Terrasse sur le Capitole avec vue sur les toits et le Vittoriano.', None, None),
'parco_acquedotti': ('Parc des Aqueducs', "Arches d'aqueducs romains au milieu des prés : la Rome de « La Grande Bellezza ».", None, None),
'appia_antica': ('Voie Appienne', 'La « reine des routes » : pavés romains, tombeaux et campagne, à pied ou à vélo.', None, None),
'villa_doria_pamphilj': (None, 'Le plus grand parc de Rome, aimé des Romains pour courir et pique-niquer.', None, None),
'villa_torlonia': (None, 'La villa de Mussolini : parc gratuit, Casina delle Civette Art nouveau à 10,50 €.', None, None),
'roseto': ('Roseraie municipale', 'Plus de mille variétés de roses, ouverte seulement au printemps.', None, None),
'villa_celimontana': (None, 'Parc tranquille à deux pas du Colisée, avec un obélisque égyptien.', None, None),
'villa_sciarra': (None, 'Petit jardin romantique avec fontaines et statues, presque inconnu des touristes.', None, None),
'villa_ada': (None, 'Grand parc naturel avec lac, ancienne résidence royale.', None, None),
'caffarella': ('Parc de la Caffarella', 'La campagne romaine en ville : fermes, nymphées et ruines.', None, None),
'orto_botanico': ('Jardin botanique', 'Jardin botanique au pied du Janicule, avec serres et bambous.', None, None),
'bioparco': (None, 'Le zoo de Rome, idéal pour ceux qui voyagent avec des enfants.', None, None),
'villa_medici': (None, "Siège de l'Académie de France : jardins Renaissance en visite guidée.", None, None),
'zodiaco': ('Belvédère du Zodiaco', 'Le point le plus haut de Rome, loin du centre : en bus ou en taxi.', None, None),
'domus_aurea': (None, "Le palais enfoui de Néron, avec un casque de réalité virtuelle qui montre les salles d'origine. Petits groupes, réserver tôt.", None, None),
'colosseo_sotterranei': ('Colisée : arène et souterrains', "Visite spéciale là où passaient gladiateurs et fauves, avec accès à l'arène.", None, None),
'caracalla': ('Thermes de Caracalla', "Les thermes les plus imposants de l'Antiquité, moins bondés que le Forum. Opéra en été.", "Thermes de Caracalla (de l'extérieur)", "Les ruines imposantes des thermes vues depuis l'avenue. Entrée non comprise."),
'ostia_antica': (None, 'Une Pompéi à 30 minutes de train : rues, tavernes, théâtre et maisons intactes.', None, None),
'palazzo_massimo': ('Musée national romain – Palazzo Massimo', 'Fresques de la villa de Livie, le Pugiliste au repos et des mosaïques extraordinaires.', None, None),
'terme_diocleziano': ('Thermes de Dioclétien', 'Immenses thermes romains avec un cloître de Michel-Ange.', None, None),
'palazzo_altemps': (None, 'Sculpture antique dans un palais Renaissance, dont le Trône Ludovisi.', None, None),
'crypta_balbi': (None, "Comment Rome s'est transformée de l'Antiquité au Moyen Âge, couche après couche.", None, None),
'mercati_traiano': ('Marchés de Trajan', 'Le « centre commercial » de la Rome antique, avec vue plongeante sur les Forums.', None, None),
'carcere_mamertino': ('Prison Mamertine', 'La prison où, selon la tradition, saint Pierre fut enfermé.', None, None),
'stadio_domiziano': ('Stade de Domitien', 'Le stade romain caché sous la Piazza Navona, qui en explique la forme.', None, None),
'vicus_caprarius': ("Vicus Caprarius – Cité de l'Eau", "Sous Trevi, une ancienne maison romaine traversée par l'eau qui alimente la fontaine.", None, None),
'mausoleo_augusto': ("Mausolée d'Auguste", 'Le tombeau circulaire du premier empereur, rouvert après des décennies de restauration.', "Mausolée d'Auguste (de l'extérieur)", "Le tombeau circulaire d'Auguste vu depuis la place."),
'san_callisto': ('Catacombes de Saint-Calixte', 'Les catacombes les plus grandes et les plus célèbres, avec la crypte des papes. Visite guidée comprise.', None, None),
'domitilla': ('Catacombes de Domitille', 'Catacombes avec une basilique souterraine et des fresques paléochrétiennes. Visite guidée comprise.', None, None),
'san_sebastiano': ('Catacombes de Saint-Sébastien', 'Catacombes avec des mausolées romains parfaitement conservés.', None, None),
'priscilla': ('Catacombes de Priscille', 'La plus ancienne représentation connue de la Vierge. Près de nos logements.', None, None),
'cecilia_metella': ('Tombeau de Cecilia Metella', 'Le mausolée-forteresse, symbole de la Voie Appienne.', None, None),
'villa_quintili': ('Villa des Quintili', 'Immense villa impériale presque déserte, hors des circuits touristiques.', None, None),
'cimitero_acattolico': ('Cimetière non catholique et pyramide de Cestius', "Le cimetière romantique de Keats et Shelley, à l'ombre d'une pyramide romaine.", None, None),
'monte_testaccio': ('Monte Testaccio (mont des tessons)', "Une colline faite entièrement d'amphores cassées : la décharge de la Rome antique. Seulement lors de visites guidées ponctuelles.", None, None),
'trastevere': (None, 'Ruelles pavées, lierre et trattorias : le quartier le plus romain de Rome, au meilleur de lui-même le soir.', None, None),
'monti': ('Quartier Monti', "Le plus ancien quartier, aujourd'hui plein de boutiques vintage, d'artisans et de placettes.", None, None),
'testaccio': ('Testaccio et son marché', 'Le quartier de la vraie cuisine romaine, avec son marché couvert et sa street food.', None, None),
'via_margutta': (None, 'La rue des artistes et de « Vacances romaines », avec ateliers et galeries.', None, None),
'piazza_mattei': ('Fontaine des Tortues', 'Petite fontaine Renaissance sur une placette cachée du Ghetto.', None, None),
'garbatella': (None, 'Cité-jardin des années 1920 : pavillons, cours et logements populaires de carte postale.', None, None),
'pigneto': (None, 'Le quartier de Pasolini, aujourd’hui fresques murales, bars et vie nocturne alternative.', None, None),
'via_giulia': (None, "Rue Renaissance droite comme un i, avec palais nobles et l'arc Farnèse.", None, None),
'piazza_farnese': (None, "Place élégante avec le palais de Michel-Ange, aujourd'hui ambassade de France.", None, None),
'via_coronari': (None, 'La rue des antiquaires, à deux pas de la Piazza Navona.', None, None),
'san_lorenzo_quartiere': ('Quartier San Lorenzo', 'Le quartier universitaire, fresques murales et bars. À quelques pas de nos logements.', None, None),
'eur': (None, "La ville rationaliste voulue pour l'Exposition de 1942, avec le « Colisée carré ».", None, None),
'ostiense_street_art': ('Ostiense et le Gazomètre', "Archéologie industrielle et grandes fresques murales, du Gazomètre aux anciens marchés généraux.", None, None),
'tor_marancia': (None, 'Vingt-deux immeubles populaires peints par des street artists internationaux.', None, None),
'governo_vecchio': (None, 'Boutiques vintage et ateliers entre Navona et Chiesa Nuova.', None, None),
'quadraro': ('Quadraro et le MURo', "Musée d'art urbain à ciel ouvert dans un quartier populaire de la Résistance.", None, None),
'porta_portese': ('Marché de Porta Portese', 'Le marché aux puces le plus célèbre de Rome : le dimanche matin seulement.', None, None),
'mercato_centrale': ('Mercato Centrale de Termini', 'Food hall réunissant les meilleurs artisans du goût sous un même toit.', None, None),
'mercato_trionfale': ('Marché Trionfale', 'Le marché couvert des Romains, à deux pas des musées du Vatican.', None, None),
'campagna_amica': ('Marché Campagna Amica au Circus Maximus', 'Produits des agriculteurs du Latium, le samedi et le dimanche.', None, None),
'cooking_class': ('Cours de cuisine romaine', 'Vous apprenez à faire des pâtes fraîches, un tiramisù ou une pizza, puis vous dégustez. En général 60-90 €.', None, None),
'food_tour': ('Food tour au Trastevere ou à Testaccio', 'Dégustations guidées : supplì, pizza al taglio, fromages et glaces. En général 60-90 €.', None, None),
'vespa_tour': ('Tour en Vespa ou en Fiat 500 vintage', 'Rome comme dans « Vacances romaines », avec chauffeur ou au volant. En général 80-150 €.', None, None),
'golf_cart': ('Tour en voiturette de golf', 'Le centre historique sans effort : idéal pour ceux qui marchent peu.', None, None),
'bici_appia': ('Voie Appienne à vélo', "Location de vélos à l'Appia Info Point, puis en route entre tombeaux et pavés romains.", None, None),
'crociera_tevere': ('Bateau sur le Tibre', 'Rome vue depuis le fleuve, aussi avec dîner à bord.', None, None),
'cinecitta': (None, 'Visite des studios de Fellini et des décors de la Rome antique.', None, None),
'explora': ('Explora – Musée des enfants', 'Musée interactif où les enfants font tout eux-mêmes.', None, None),
'opera_caracalla': ('Opéra aux thermes de Caracalla', 'Opéra et ballet en plein air parmi les ruines des thermes. En été seulement.', None, None),
}
G = {
'tivoli': ("Tivoli : Villa d'Este et Villa Adriana", "Deux sites UNESCO en une journée : la villa de l'empereur Hadrien et le jardin aux cent fontaines.", ['Villa Adriana', "Villa d'Este", 'centre de Tivoli'], 'Fermé le lundi matin'),
'pompei': ('Pompéi', 'La ville ensevelie par le Vésuve. Frecciarossa jusqu’à Naples puis Circumvesuviana : longue journée mais inoubliable.', ['Fouilles de Pompéi'], None),
'firenze': ('Florence en un jour', 'En Frecciarossa on y est en une heure et demie : le meilleur de la Renaissance en une journée.', ['Duomo', 'Ponte Vecchio', 'Piazza della Signoria', 'Offices (facultatif)'], None),
'orvieto': (None, "Ville étrusque sur un rocher de tuf, avec l'une des plus belles cathédrales gothiques d'Italie et un labyrinthe de grottes.", ['Duomo', 'Puits de Saint-Patrick', 'Orvieto souterraine'], None),
'napoli': ('Naples en un jour', "Une heure dix de Frecciarossa jusqu'à la ville la plus vivante d'Italie, et sa pizza.", ['centre historique', 'Christ voilé', 'front de mer', 'pizza'], None),
'castelli': ('Castelli Romani', 'Villages sur les collines volcaniques : vin de Frascati, porchetta d’Ariccia, fraises des bois de Nemi et palais des papes.', ['Frascati', 'Castel Gandolfo', 'Ariccia', 'Nemi'], 'Le palais pontifical de Castel Gandolfo est payant'),
'tuscia': ('Civita di Bagnoregio et le Parc des Monstres', "« La ville qui meurt » sur son éperon de tuf et le jardin de sculptures monstrueuses qui enchanta Dalí. Voiture nécessaire.", ['Civita di Bagnoregio', 'Bois sacré de Bomarzo'], None),
'assisi': ('Assise', 'La ville de saint François, avec la basilique peinte à fresque par Giotto.', ['Basilique Saint-François', 'centre historique'], None),
'cerveteri': ('Cerveteri : nécropole étrusque', 'Une cité des morts étrusque classée UNESCO, avec des tombes en forme de maison. La mer de Ladispoli est tout près.', ['Nécropole de la Banditaccia', 'Musée Cerite'], None),
'tarquinia': ('Tarquinia : tombes peintes', 'Les plus belles tombes étrusques à fresques du monde, aux couleurs encore vives après 2500 ans.', ['Nécropole de Monterozzi', 'Musée national de Tarquinia'], None),
'ninfa': ('Jardin de Ninfa et Sermoneta', "Le « plus romantique jardin du monde » parmi les ruines d'une ville médiévale. Ouvert certains jours seulement, sur réservation.", ['Jardin de Ninfa', 'village de Sermoneta'], "Ouverture saisonnière, d'avril à novembre"),
'sperlonga': (None, 'Village blanc surplombant la mer et parmi les plus belles plages du Latium. Idéal en été.', ['village blanc', 'plage', 'Grotte de Tibère'], 'Conseillée de juin à septembre'),
'viterbo': ('Viterbe', 'La cité médiévale des papes, avec des quartiers intacts et des sources chaudes gratuites où se baigner.', ['Palais des Papes', 'quartier San Pellegrino', 'Viterbe souterraine', 'thermes'], None),
'bracciano': ('Lac et château de Bracciano', 'Château médiéval sur un lac volcanique, avec promenade et déjeuner de poisson du lac.', ['Château Orsini-Odescalchi', 'bord du lac'], None),
'subiaco': ('Subiaco : monastères de saint Benoît', 'Des monastères accrochés à la roche où saint Benoît fonda son ordre.', ['Sacro Speco', 'Monastère Sainte-Scholastique'], None),
'montecassino': ('Abbaye du Mont-Cassin', 'L’abbaye de saint Benoît, détruite et reconstruite après la bataille de 1944.', ['Abbaye', 'cimetière militaire polonais'], None),
'mare_ostia': ('La mer à Ostie', 'La plage des Romains, accessible avec le ticket urbain. En été seulement.', ['plage'], None),
}
S = {
'trastevere': (None, 'Le cœur des soirées romaines : apéritif Piazza San Calisto, dîner en trattoria, puis les marches de la Piazza Trilussa.'),
'monti': ('Quartier Monti', 'Apéritif Piazza Madonna dei Monti entre Romains et touristes, puis dîner autour de la Via Panisperna.'),
'campo_navona': ("Campo de' Fiori et Navona", "Bars à vin Via del Governo Vecchio et Piazza del Fico, dîner près de Navona, soirée à Campo de' Fiori."),
'ghetto': ('Ghetto juif', "Dîner judéo-romain : artichauts à la juive et filets de morue entre le Portique d'Octavie et la Via del Portico."),
'testaccio': (None, 'La cuisine romaine la plus authentique, de la queue de bœuf à la cacio e pepe ; puis des bars jusque tard.'),
'pigneto': (None, 'Zone piétonne alternative, vins nature et bières artisanales. Près de nos logements.'),
'tridente': ("Place d'Espagne et Piazza del Popolo", 'Apéritif élégant et terrasses avec vue entre la Via Margutta et la Piazza del Popolo.'),
'prati': (None, 'Apéritifs raffinés et restaurants tranquilles, parfaits après une journée au Vatican.'),
'san_lorenzo': (None, 'Le quartier universitaire : bon marché, animé, plein de trattorias et de pubs. À deux pas de chez nous.'),
'ostiense': (None, 'Ancienne zone industrielle avec bars, restaurants et clubs ; Eataly pour tout trouver au même endroit.'),
'ponte_milvio': (None, "L'apéritif des jeunes Romains, avec le pont des cadenas."),
'piazza_bologna': ('Quartier Piazza Bologna (près de chez nous)', 'Pour une soirée tranquille près de nos logements : retrouvez nos adresses dans la rubrique Manger.'),
}
