# Português. A: id -> (nome ou None, desc, nome_fora ou None, desc_fora ou None)
A = {
'illusioni': ('Museu das Ilusões', 'Mais de 70 ilusões óticas e salas interativas: divertido para todas as idades.', None, None),
'cappuccini': ('Cripta dos Capuchinhos', 'Capelas decoradas com os ossos de milhares de frades: macabra e única no mundo.', None, None),
'montemartini': (None, 'Estátuas romanas expostas entre as turbinas de uma antiga central elétrica.', None, None),
'serra_moresca': ('Estufa Mourisca da Villa Torlonia', 'Estufa do século XIX em estilo Alhambra, com vitrais coloridos. Fechada em julho e agosto.', None, None),
'museo_luce': ('Museu da Luz', 'A física da luz contada com instalações para tocar.', None, None),
'welcome_rome': (None, 'Viagem multimédia pelos 2700 anos da cidade, ótima como introdução.', None, None),
'barracco': ('Museu Barracco', 'Pequena coleção de escultura egípcia, assíria, grega e romana.', None, None),
'museo_mura': ('Museu das Muralhas', 'Caminha-se dentro da Porta San Sebastiano e ao longo das Muralhas Aurelianas.', None, None),
'lab_mente': ('Museu Laboratório da Mente', 'No antigo manicómio de Santa Maria della Pietà: comovente e pouco conhecido.', None, None),
'anime_purgatorio': ('Museu das Almas do Purgatório', 'Minúscula coleção de "marcas do além" dentro de uma igreja neogótica.', None, None),
'buco_serratura': ('Buraco da fechadura do Aventino', 'São Pedro emoldurado na fechadura dos Cavaleiros de Malta.', None, None),
'coppede': ('Bairro Coppedè', 'Arquitetura de conto de fadas entre Arte Nova, gótico e medieval.', None, None),
'palazzo_valentini': ('Domus romanas do Palazzo Valentini', 'Casas romanas debaixo de um palácio, reanimadas por projeções multimédia.', None, None),
'case_celio': ('Casas romanas do Celio', 'Habitações romanas com frescos por baixo de uma basílica.', None, None),
'galleria_spada': (None, 'Famosa pela falsa perspetiva de Borromini: 9 metros que parecem 35.', None, None),
'galleria_sciarra': (None, 'Pátio Arte Nova com frescos, escondido a dois passos da Via del Corso.', None, None),
'maxxi': (None, 'Arte contemporânea no edifício projetado por Zaha Hadid.', None, None),
'dreamers': (None, 'Salas imersivas e coloridas, pensadas para fotografias.', None, None),
'ikono': (None, 'Experiência sensorial em salas temáticas.', None, None),
'time_elevator': (None, 'Cinema 5D com cadeiras móveis sobre a história de Roma, ideal para crianças.', None, None),
'colosseo': ('Coliseu, Fórum Romano e Palatino', 'O símbolo de Roma e o coração da cidade antiga, com um único bilhete.', 'Coliseu (por fora)', 'O Coliseu por fora, com o Arco de Constantino e a vista sobre o Fórum. Entrada não incluída.'),
'pantheon': ('Panteão', 'O templo romano mais bem conservado, com a maior cúpula de betão alguma vez construída.', 'Panteão (por fora)', 'A fachada do Panteão e a Piazza della Rotonda com a sua fonte. Entrada não incluída.'),
'trevi': ('Fontana di Trevi', 'A fonte mais famosa do mundo. Vista livre a partir da praça, 2€ para descer junto à água.', None, None),
'navona': (None, 'Praça barroca com a Fonte dos Quatro Rios de Bernini.', None, None),
'spagna': ('Praça de Espanha e Trinità dei Monti', 'A escadaria mais famosa de Roma, com a Barcaccia aos seus pés.', None, None),
'capitolini': ('Museus Capitolinos e Piazza del Campidoglio', 'O museu público mais antigo do mundo, na praça desenhada por Miguel Ângelo.', 'Piazza del Campidoglio e terraço sobre o Fórum', 'A Piazza del Campidoglio de Miguel Ângelo e o terraço gratuito sobre o Fórum Romano.'),
'castel_santangelo': ("Castelo de Sant'Angelo", 'De mausoléu de Adriano a fortaleza dos papas, com terraço panorâmico.', "Castelo de Sant'Angelo (por fora)", 'O castelo visto da Ponte dos Anjos e da margem do Tibre. Entrada não incluída.'),
'vittoriano': (None, 'Monumento imponente de entrada livre; o terraço panorâmico custa 18€.', None, None),
'fori_imperiali': (None, 'Passeio junto aos fóruns de César, Augusto e Trajano, visíveis a partir da rua.', None, None),
'ghetto': ('Gueto judeu e Pórtico de Octávia', 'O bairro judeu mais antigo da Europa, entre ruínas romanas e alcachofras à judia.', None, None),
'popolo': (None, 'Grande praça neoclássica com o obelisco e as igrejas gémeas.', None, None),
'campo_fiori': (None, 'Mercado de manhã, vida noturna à noite, com a estátua de Giordano Bruno.', None, None),
'bocca_verita': ('Boca da Verdade', 'A lendária máscara que morde a mão dos mentirosos.', 'Boca da Verdade (do pórtico)', 'A Boca da Verdade vê-se a partir do portão do pórtico, mesmo sem entrar.'),
'torre_argentina': (None, 'A área sagrada onde César foi assassinado, hoje também colónia de gatos.', None, None),
'teatro_marcello': ('Teatro de Marcelo', 'Teatro romano sobre o qual foi construído um palácio habitado.', None, None),
'isola_tiberina': ('Ilha Tiberina', 'A única ilha do Tibre, ligada pela ponte romana mais antiga ainda em uso.', None, None),
'circo_massimo': ('Circo Máximo', 'O maior estádio da Antiguidade, hoje um grande relvado.', None, None),
'ara_pacis': (None, 'O altar de Augusto no pavilhão de Richard Meier.', 'Ara Pacis (por fora)', 'O altar de Augusto visto através do pavilhão de vidro de Richard Meier.'),
'musei_vaticani': ('Museus do Vaticano e Capela Sistina', 'Uma das maiores coleções do mundo, até ao Juízo Final de Miguel Ângelo. Online sem filas 25€.', None, None),
'san_pietro': ('Basílica de São Pedro', 'A maior igreja da cristandade, com a Pietà de Miguel Ângelo.', None, None),
'piazza_san_pietro': ('Praça de São Pedro', 'A colunata de Bernini abraça os fiéis.', None, None),
'cupola': ('Cúpula de São Pedro', 'Elevador mais 320 degraus (10€) ou 551 degraus a pé (8€) até à vista mais famosa de Roma.', None, None),
'grotte_vaticane': ('Grutas do Vaticano', 'Os túmulos dos papas por baixo da basílica.', None, None),
'necropoli': ('Necrópole do Vaticano (Scavi)', 'Visita guiada ao túmulo de São Pedro: reservar com muita antecedência.', None, None),
'giardini_vaticani': ('Jardins do Vaticano', 'Visita guiada aos jardins dos papas, só com reserva. A partir de 20€, 40€ com o autocarro panorâmico.', None, None),
'ponte_santangelo': ("Ponte de Sant'Angelo", 'A ponte dos anjos de Bernini, em frente ao castelo.', None, None),
'borgo_pio': ('Borgo Pio e Passetto di Borgo', 'Ruelas por baixo do corredor secreto que levava os papas ao castelo.', None, None),
'prati': ('Prati e Via Cola di Rienzo', 'Bairro elegante do final do século XIX, ótimo para compras.', None, None),
'palazzaccio': ('Palácio da Justiça', 'O "Palazzaccio", monumental e controverso.', None, None),
'laterano': ('São João de Latrão', 'A catedral de Roma, mãe de todas as igrejas do mundo.', None, None),
'santa_maria_maggiore': ('Santa Maria Maior', 'Mosaicos do século V e teto dourado com o primeiro ouro das Américas.', None, None),
'san_paolo': ('São Paulo Extramuros', 'Basílica imensa com os retratos de todos os papas e um claustro esplêndido.', None, None),
'vincoli': ('São Pedro Acorrentado', 'O Moisés de Miguel Ângelo e as correntes de São Pedro.', None, None),
'san_clemente': ('São Clemente e os seus subterrâneos', 'Três níveis sobrepostos: igreja medieval, basílica do século IV e templo de Mitra. Escavações com reserva.', None, None),
'santa_maria_trastevere': (None, 'Uma das igrejas mais antigas de Roma, com mosaicos dourados na fachada e na abside.', None, None),
'san_luigi': (None, 'Três obras-primas de Caravaggio sobre a vida de São Mateus, gratuitas.', None, None),
'sant_ignazio': ('Santo Inácio', 'A falsa cúpula pintada de Andrea Pozzo: um espelho no centro revela o engano.', None, None),
'santa_maria_popolo': (None, 'Dois Caravaggio e a Capela Chigi de Rafael e Bernini.', None, None),
'gesu': ('Igreja do Gesù', 'Obra-prima barroca dos jesuítas; todos os dias às 17h30 a "máquina" do altar de Santo Inácio.', None, None),
'minerva': (None, 'A única igreja gótica de Roma, com o elefantezinho de Bernini à frente.', None, None),
'scala_santa': ('Escada Santa', 'A escada que Jesus teria subido perante Pilatos: os fiéis sobem-na de joelhos.', None, None),
'vittoria': (None, 'O Êxtase de Santa Teresa, obra-prima de Bernini.', None, None),
'sant_agostino': ('Santo Agostinho', 'A Madona dos Peregrinos de Caravaggio.', None, None),
'aracoeli': (None, 'Chega-se subindo 124 degraus; lá dentro, frescos de Pinturicchio.', None, None),
'santa_cecilia': (None, 'A estátua da santa esculpida tal como foi encontrada e um raro fresco de Cavallini.', None, None),
'santa_prassede': (None, 'A capela de São Zenão, totalmente coberta de mosaicos dourados.', None, None),
'quattro_fontane': (None, 'A obra-prima de Borromini: uma cúpula oval do tamanho de um pilar de São Pedro.', None, None),
'sant_andrea_quirinale': ("Sant'Andrea al Quirinale", 'A "pérola" de Bernini, a cem metros da do seu rival Borromini.', None, None),
'santo_stefano_rotondo': (None, 'Igreja circular do século V, com crus frescos de mártires.', None, None),
'quattro_coronati': (None, 'Mosteiro fortificado com a capela de São Silvestre e um claustro escondido.', None, None),
'santa_sabina': (None, 'Basílica do século V com a porta de madeira original e o Jardim das Laranjeiras ao lado.', None, None),
'tempietto_bramante': ('Tempietto de Bramante', 'A joia do Renascimento, onde segundo a tradição Pedro foi crucificado.', None, None),
'santa_maria_angeli': (None, 'Miguel Ângelo transformou as Termas de Diocleciano em igreja; no chão, uma meridiana.', None, None),
'sant_ivo': ("Sant'Ivo alla Sapienza", 'A cúpula em espiral de Borromini; normalmente aberta só ao domingo de manhã.', None, None),
'san_lorenzo': ('São Lourenço Extramuros', 'Basílica medieval com claustro, junto ao cemitério do Verano.', None, None),
'santa_costanza': ('Mausoléu de Santa Constança', 'Mausoléu do século IV com mosaicos de vindima ainda pagãos.', None, None),
'chiostro_bramante': ('Claustro de Bramante', 'Claustro renascentista com exposições temporárias e cafetaria virada para Santa Maria della Pace.', None, None),
'cosma_damiano': ('Santos Cosme e Damião', 'Mosaico da abside do século VI e um grande presépio napolitano do século XVIII.', None, None),
'galleria_borghese': ('Galeria Borghese', 'Bernini e Caravaggio numa villa barroca. Reserva obrigatória, turnos de 2 horas.', None, None),
'villa_borghese': (None, 'O parque mais famoso de Roma: avenidas, lago com barcos a remos, aluguer de bicicletas e riquexós.', None, None),
'pincio': ('Terraço do Pincio', 'Vista sobre a Piazza del Popolo e as cúpulas, esplêndida ao pôr do sol.', None, None),
'giardino_aranci': ('Jardim das Laranjeiras', 'O pôr do sol mais romântico de Roma, entre laranjeiras sobre o Tibre.', None, None),
'gianicolo': ('Miradouro do Gianicolo', 'O terraço mais amplo sobre a cidade; ao meio-dia dispara-se um tiro de canhão.', None, None),
'fontanone': ('Fontanone do Gianicolo', 'A fonte monumental da Acqua Paola, com vista sobre o Trastevere.', None, None),
'terrazza_caffarelli': ('Terraço Caffarelli', 'Terraço no Capitólio com vista sobre os telhados e o Vittoriano.', None, None),
'parco_acquedotti': ('Parque dos Aquedutos', 'Arcos de aquedutos romanos no meio dos prados: a Roma de "A Grande Beleza".', None, None),
'appia_antica': ('Via Ápia Antiga', 'A "rainha das estradas": lajes romanas, túmulos e campo, a pé ou de bicicleta.', None, None),
'villa_doria_pamphilj': (None, 'O maior parque de Roma, adorado pelos romanos para correr e fazer piqueniques.', None, None),
'villa_torlonia': (None, 'A villa de Mussolini: parque gratuito, Casina delle Civette em Arte Nova a 10,50€.', None, None),
'roseto': ('Roseiral Municipal', 'Mais de mil variedades de rosas, aberto só na primavera.', None, None),
'villa_celimontana': (None, 'Parque tranquilo a dois passos do Coliseu, com um obelisco egípcio.', None, None),
'villa_sciarra': (None, 'Pequeno jardim romântico com fontes e estátuas, quase desconhecido dos turistas.', None, None),
'villa_ada': (None, 'Grande parque natural com lago, antiga residência real.', None, None),
'caffarella': ('Parque da Caffarella', 'Campo romano dentro da cidade: quintas, ninfeus e ruínas.', None, None),
'orto_botanico': ('Jardim Botânico', 'Jardim botânico no sopé do Gianicolo, com estufas e bambus.', None, None),
'bioparco': (None, 'O jardim zoológico de Roma, ideal para quem viaja com crianças.', None, None),
'villa_medici': (None, 'Sede da Academia de França: jardins renascentistas com visita guiada.', None, None),
'zodiaco': ('Miradouro do Zodiaco', 'O ponto mais alto de Roma, longe do centro: chega-se de autocarro ou táxi.', None, None),
'domus_aurea': (None, 'O palácio enterrado de Nero, com óculos de realidade virtual que mostram as salas como eram. Grupos pequenos, reservar cedo.', None, None),
'colosseo_sotterranei': ('Coliseu: arena e subterrâneos', 'Visita especial por onde passavam gladiadores e feras, com acesso à arena.', None, None),
'caracalla': ('Termas de Caracala', 'As termas mais imponentes da Antiguidade, menos cheias do que o Fórum. No verão, ópera.', 'Termas de Caracala (por fora)', 'As imponentes ruínas das termas vistas da avenida. Entrada não incluída.'),
'ostia_antica': ('Óstia Antiga', 'Uma Pompeia a 30 minutos de comboio: ruas, tabernas, teatro e casas intactas.', None, None),
'palazzo_massimo': ('Museu Nacional Romano – Palazzo Massimo', 'Frescos da villa de Lívia, o Pugilista em repouso e mosaicos extraordinários.', None, None),
'terme_diocleziano': ('Termas de Diocleciano', 'Enormes termas romanas com um claustro de Miguel Ângelo.', None, None),
'palazzo_altemps': (None, 'Escultura antiga num palácio renascentista, incluindo o Trono Ludovisi.', None, None),
'crypta_balbi': (None, 'Como Roma se transformou da Antiguidade à Idade Média, camada a camada.', None, None),
'mercati_traiano': ('Mercados de Trajano', 'O "centro comercial" da Roma antiga, com vista de cima sobre os Fóruns.', None, None),
'carcere_mamertino': ('Cárcere Mamertino', 'A prisão onde, segundo a tradição, esteve preso São Pedro.', None, None),
'stadio_domiziano': ('Estádio de Domiciano', 'O estádio romano escondido debaixo da Piazza Navona, que explica a sua forma.', None, None),
'vicus_caprarius': ('Vicus Caprarius – Cidade da Água', 'Debaixo de Trevi, uma antiga casa romana atravessada pela água que alimenta a fonte.', None, None),
'mausoleo_augusto': ('Mausoléu de Augusto', 'O túmulo circular do primeiro imperador, reaberto após décadas de restauro.', 'Mausoléu de Augusto (por fora)', 'O túmulo circular de Augusto visto da praça.'),
'san_callisto': ('Catacumbas de São Calisto', 'As catacumbas maiores e mais famosas, com a cripta dos papas. Visita guiada incluída.', None, None),
'domitilla': ('Catacumbas de Domitila', 'Catacumbas com uma basílica subterrânea e frescos paleocristãos. Visita guiada incluída.', None, None),
'san_sebastiano': ('Catacumbas de São Sebastião', 'Catacumbas com mausoléus romanos perfeitamente conservados.', None, None),
'priscilla': ('Catacumbas de Priscila', 'A mais antiga representação conhecida da Virgem. Perto dos nossos alojamentos.', None, None),
'cecilia_metella': ('Túmulo de Cecília Metela', 'O mausoléu-fortaleza, símbolo da Via Ápia.', None, None),
'villa_quintili': ('Villa dos Quintílios', 'Enorme villa imperial quase deserta, fora dos circuitos turísticos.', None, None),
'cimitero_acattolico': ('Cemitério Acatólico e Pirâmide Céstia', 'O cemitério romântico de Keats e Shelley, à sombra de uma pirâmide romana.', None, None),
'monte_testaccio': ('Monte Testaccio (dos cacos)', 'Uma colina feita só de ânforas partidas: a lixeira da Roma antiga. Só com visitas guiadas ocasionais.', None, None),
'trastevere': (None, 'Ruelas empedradas, hera e trattorias: o bairro mais romano de Roma, no seu melhor à noite.', None, None),
'monti': ('Bairro de Monti', 'O bairro mais antigo, hoje cheio de lojas vintage, artesãos e pracinhas.', None, None),
'testaccio': ('Testaccio e o seu mercado', 'O bairro da verdadeira cozinha romana, com o mercado coberto e comida de rua.', None, None),
'via_margutta': (None, 'A rua dos artistas e de "Férias em Roma", com ateliês e galerias.', None, None),
'piazza_mattei': ('Fonte das Tartarugas', 'Pequena fonte renascentista numa pracinha escondida do Gueto.', None, None),
'garbatella': (None, 'Cidade-jardim dos anos 20: moradias, pátios e bairros populares de postal.', None, None),
'pigneto': (None, 'O bairro de Pasolini, hoje murais, bares e vida noturna alternativa.', None, None),
'via_giulia': (None, 'Rua renascentista direita como uma flecha, com palácios nobres e o arco Farnese.', None, None),
'piazza_farnese': (None, 'Praça elegante com o palácio de Miguel Ângelo, hoje embaixada de França.', None, None),
'via_coronari': (None, 'A rua dos antiquários, a dois passos da Piazza Navona.', None, None),
'san_lorenzo_quartiere': ('Bairro de San Lorenzo', 'O bairro universitário, murais e bares. A poucos passos dos nossos alojamentos.', None, None),
'eur': (None, 'A cidade racionalista criada para a Exposição de 1942, com o "Coliseu quadrado".', None, None),
'ostiense_street_art': ('Ostiense e o Gasómetro', 'Arqueologia industrial e grandes murais, do Gasómetro aos antigos Mercados Gerais.', None, None),
'tor_marancia': (None, 'Vinte e dois prédios populares pintados por artistas urbanos internacionais.', None, None),
'governo_vecchio': (None, 'Lojas vintage e oficinas entre Navona e Chiesa Nuova.', None, None),
'quadraro': ('Quadraro e o MURo', 'Museu de arte urbana ao ar livre num bairro popular da Resistência.', None, None),
'porta_portese': ('Mercado de Porta Portese', 'A feira da ladra mais famosa de Roma: só ao domingo de manhã.', None, None),
'mercato_centrale': ('Mercato Centrale de Termini', 'Mercado gastronómico com os melhores artesãos do sabor sob o mesmo teto.', None, None),
'mercato_trionfale': ('Mercado Trionfale', 'O mercado coberto dos romanos, a dois passos dos Museus do Vaticano.', None, None),
'campagna_amica': ('Mercado Campagna Amica no Circo Máximo', 'Produtos dos agricultores do Lácio, ao sábado e ao domingo.', None, None),
'cooking_class': ('Aula de cozinha romana', 'Aprende a fazer massa fresca, tiramisù ou pizza e depois come o que cozinhou. Normalmente 60-90€.', None, None),
'food_tour': ('Food tour no Trastevere ou em Testaccio', 'Provas guiadas de supplì, pizza ao corte, queijos e gelado. Normalmente 60-90€.', None, None),
'vespa_tour': ('Passeio de Vespa ou de Fiat 500 antigo', 'Roma como em "Férias em Roma", com motorista ou ao volante. Normalmente 80-150€.', None, None),
'golf_cart': ('Passeio de carrinho de golfe', 'O centro histórico sem esforço: ideal para quem anda pouco.', None, None),
'bici_appia': ('Via Ápia de bicicleta', 'Aluguer de bicicletas no Appia Info Point e a pedalar entre túmulos e lajes romanas.', None, None),
'crociera_tevere': ('Barco no Tibre', 'Roma vista do rio, também com jantar a bordo.', None, None),
'cinecitta': (None, 'Visita aos estúdios de Fellini e aos cenários da Roma antiga.', None, None),
'explora': ('Explora – Museu das Crianças', 'Museu interativo onde as crianças fazem tudo sozinhas.', None, None),
'opera_caracalla': ('Ópera nas Termas de Caracala', 'Ópera e bailado ao ar livre entre as ruínas das termas. Só no verão.', None, None),
}
G = {
'tivoli': ("Tivoli: Villa d'Este e Villa Adriana", 'Dois sítios UNESCO num só dia: a villa do imperador Adriano e o jardim das cem fontes.', ['Villa Adriana', "Villa d'Este", 'centro de Tivoli'], 'Fechado à segunda-feira de manhã'),
'pompei': ('Pompeia', 'A cidade soterrada pelo Vesúvio. Frecciarossa até Nápoles e depois Circumvesuviana: dia longo mas inesquecível.', ['Ruínas de Pompeia'], None),
'firenze': ('Florença num dia', 'De Frecciarossa chega-se em hora e meia: o melhor do Renascimento num dia.', ['Duomo', 'Ponte Vecchio', 'Piazza della Signoria', 'Uffizi (opcional)'], None),
'orvieto': (None, 'Cidade etrusca numa rocha de tufo, com uma das catedrais góticas mais bonitas de Itália e um labirinto de grutas.', ['Duomo', 'Poço de São Patrício', 'Orvieto subterrânea'], None),
'napoli': ('Nápoles num dia', 'Uma hora e dez de Frecciarossa até à cidade mais viva de Itália, e a sua pizza.', ['centro histórico', 'Cristo Velado', 'marginal', 'pizza'], None),
'castelli': ('Castelli Romani', 'Vilas em colinas vulcânicas: vinho de Frascati, porchetta de Ariccia, morangos silvestres de Nemi e o palácio dos papas.', ['Frascati', 'Castel Gandolfo', 'Ariccia', 'Nemi'], 'O Palácio Papal de Castel Gandolfo é pago'),
'tuscia': ('Civita di Bagnoregio e o Parque dos Monstros', '"A cidade que morre" no seu esporão de tufo e o jardim de esculturas monstruosas que encantou Dalí. É preciso carro.', ['Civita di Bagnoregio', 'Bosque Sagrado de Bomarzo'], None),
'assisi': ('Assis', 'A cidade de São Francisco, com a basílica pintada a fresco por Giotto.', ['Basílica de São Francisco', 'centro histórico'], None),
'cerveteri': ('Cerveteri: necrópole etrusca', 'Uma cidade dos mortos etrusca, património UNESCO, com túmulos em forma de casa. Perto fica o mar de Ladispoli.', ['Necrópole da Banditaccia', 'Museu Cerite'], None),
'tarquinia': ('Tarquinia: túmulos pintados', 'Os túmulos etruscos com frescos mais bonitos do mundo, com cores ainda vivas após 2500 anos.', ['Necrópole de Monterozzi', 'Museu Nacional Tarquiniense'], None),
'ninfa': ('Jardim de Ninfa e Sermoneta', 'O "jardim mais romântico do mundo" entre as ruínas de uma cidade medieval. Aberto só em alguns dias, com reserva.', ['Jardim de Ninfa', 'vila de Sermoneta'], 'Abertura sazonal, de abril a novembro'),
'sperlonga': (None, 'Vila branca debruçada sobre o mar e algumas das melhores praias do Lácio. Ideal no verão.', ['vila branca', 'praia', 'Gruta de Tibério'], 'Recomendada de junho a setembro'),
'viterbo': (None, 'A cidade medieval dos papas, com bairros intactos e termas livres onde tomar banho.', ['Palácio dos Papas', 'bairro de San Pellegrino', 'Viterbo subterrânea', 'termas'], None),
'bracciano': ('Lago e Castelo de Bracciano', 'Castelo medieval num lago vulcânico, com passeio e almoço de peixe do lago.', ['Castelo Orsini-Odescalchi', 'margem do lago'], None),
'subiaco': ('Subiaco: mosteiros de São Bento', 'Mosteiros agarrados à rocha onde São Bento fundou a sua ordem.', ['Sacro Speco', 'Mosteiro de Santa Escolástica'], None),
'montecassino': ('Abadia de Montecassino', 'A abadia de São Bento, destruída e reconstruída após a batalha de 1944.', ['Abadia', 'cemitério militar polaco'], None),
'mare_ostia': ('Praia de Óstia', 'A praia dos romanos, com o bilhete de transporte urbano. Só no verão.', ['praia'], None),
}
S = {
'trastevere': (None, 'O coração da noite romana: aperitivo na Piazza San Calisto, jantar numa trattoria e depois os degraus da Piazza Trilussa.'),
'monti': ('Bairro de Monti', 'Aperitivo na Piazza Madonna dei Monti entre romanos e turistas, depois jantar à volta da Via Panisperna.'),
'campo_navona': ("Campo de' Fiori e Navona", "Bares de vinho na Via del Governo Vecchio e na Piazza del Fico, jantar perto de Navona, noite em Campo de' Fiori."),
'ghetto': ('Gueto judeu', 'Jantar judaico-romano: alcachofras à judia e filetes de bacalhau entre o Pórtico de Octávia e a Via del Portico.'),
'testaccio': (None, 'A cozinha romana mais genuína, do rabo de boi à cacio e pepe; depois bares até tarde.'),
'pigneto': (None, 'Zona pedonal alternativa, vinhos naturais e cervejas artesanais. Perto dos nossos alojamentos.'),
'tridente': ('Praça de Espanha e Piazza del Popolo', 'Aperitivo elegante e terraços com vista entre a Via Margutta e a Piazza del Popolo.'),
'prati': (None, 'Aperitivos requintados e restaurantes tranquilos, perfeitos depois de um dia no Vaticano.'),
'san_lorenzo': (None, 'O bairro universitário: barato, animado, cheio de trattorias e pubs. A dois passos de casa.'),
'ostiense': (None, 'Antiga zona industrial com bares, restaurantes e discotecas; Eataly para ter tudo num só sítio.'),
'ponte_milvio': (None, 'O aperitivo dos jovens romanos, com a ponte dos cadeados.'),
'piazza_bologna': ('Zona da Piazza Bologna (perto de casa)', 'Para uma noite tranquila perto dos nossos alojamentos: encontra os locais recomendados na secção Comer.'),
}
